### ISSUE TITLE
Bug: scan cache fails if a cached snapshot is empty

### ISSUE THREAD

**Issue by Wauplin** [huggingface/huggingface_hub#1050]
*First reported by @lewtun [on slack](https://huggingface.slack.com/archives/C02V5EA0A95/p1663170171336839?thread_ts=1661870791.101369&cid=C02V5EA0A95) (internal url)*:

```
Traceback (most recent call last):
  File "/Users/lewtun/miniconda3/envs/hf/bin/huggingface-cli", line 8, in <module>
    sys.exit(main())
  File "/Users/lewtun/miniconda3/envs/hf/lib/python3.9/site-packages/huggingface_hub/commands/huggingface_cli.py", line 43, in main
    service.run()
  File "/Users/lewtun/miniconda3/envs/hf/lib/python3.9/site-packages/huggingface_hub/commands/cache.py", line 56, in run
    hf_cache_info = scan_cache_dir(self.cache_dir)
  File "/Users/lewtun/miniconda3/envs/hf/lib/python3.9/site-packages/huggingface_hub/utils/_cache_manager.py", line 596, in scan_cache_dir
    repos.add(_scan_cached_repo(repo_path))
  File "/Users/lewtun/miniconda3/envs/hf/lib/python3.9/site-packages/huggingface_hub/utils/_cache_manager.py", line 722, in _scan_cached_repo
    last_modified=max(
ValueError: max() arg is an empty sequence
```

**Comment by lewtun** [comment]
Temporary workaround is to delete the empty repos in the cache with something like:

````
find ~/.cache/huggingface -type d -empty --delete
```
