### ISSUE TITLE
Flaky error "File already exist" during symlink creation

### ISSUE THREAD

**Issue by sgugger** [huggingface/huggingface_hub#1108]
Since the last release of `huggingface_hub` we start to have the following flaky error in the Transformers CI (I can't reproduce it locally and it does not appear all the time):
```
src = '/home/circleci/.cache/huggingface/hub/models--hf-internal-testing--tiny-random-distilbert/blobs/b35fd67976a8dd4fb8184d68ae755750f6745bb8'
dst = '/home/circleci/.cache/huggingface/hub/models--hf-internal-testing--tiny-random-distilbert/snapshots/2ef615d573271690c9822df720b8024148d6715a/tokenizer.json'
new_blob = False

    def _create_relative_symlink(src: str, dst: str, new_blob: bool = False) -> None:
        """Create a symbolic link named dst pointing to src as a relative path to dst.
    
        The relative part is mostly because it seems more elegant to the author.
    
        The result layout looks something like
            └── [ 128]  snapshots
                ├── [ 128]  2439f60ef33a0d46d85da5001d52aeda5b00ce9f
                │   ├── [  52]  README.md -> ../../blobs/d7edf6bd2a681fb0175f7735299831ee1b22b812
                │   └── [  76]  pytorch_model.bin -> ../../blobs/403450e234d65943a7dcf7e05a771ce3c92faa84dd07db4ac20f592037a1e4bd
    
        If symlinks cannot be created on this platform (most likely to be Windows), the
        workaround is to avoid symlinks by having the actual file in `dst`. If it is a new
        file (`new_blob=True`), we move it to `dst`. If it is not a new file
        (`new_blob=False`), we don't know if the blob file is already referenced elsewhere.
        To avoid breaking existing cache, the file is duplicated on the disk.
    
        In case symlinks are not supported, a warning message is displayed to the user once
        when loading `huggingface_hub`. The warning message can be disable with the
        `DISABLE_SYMLINKS_WARNING` environment variable.
        """
        relative_src = os.path.relpath(src, start=os.path.dirname(dst))
        try:
            os.remove(dst)
        except OSError:
            pass
    
        cache_dir = os.path.dirname(os.path.commonpath([src, dst]))
        if are_symlinks_supported(cache_dir=cache_dir):
>           os.symlink(relative_src, dst)
E           FileExistsError: [Errno 17] File exists: '../../blobs/b35fd67976a8dd4fb8184d68ae755750f6745bb8' -> '/home/circleci/.cache/huggingface/hub/models--hf-internal-testing--tiny-random-distilbert/snapshots/2ef615d573271690c9822df720b8024148d6715a/tokenizer.json'

../.pyenv/versions/3.7.12/lib/python3.7/site-packages/huggingface_hub/file_download.py:808: FileExistsError
```

I think it can be easily solved by not doing the symlink if it already exists, not sure why it started happening. Maybe its two tests in parallel downloading the same model and both trying to do it at the same time?

You can find the full tracebacks [here](https://app.circleci.com/pipelines/github/huggingface/transformers/49095/workflows/4a038248-86c6-4288-94d5-b51cc1263078/jobs/587610/artifacts).

cc @Wauplin

**Comment by Wauplin** [comment]
@sgugger thanks for reporting this. Indeed it really seems to come from a concurrent download. There is a `os.remove` before `os.symlink` but as both are not made "as a transaction" it is possible to have a concurrency issue. Since last release I have added an extra step to check if symlinks are supported on the platform (before creating it) so maybe that added extra milliseconds and created the bug in your CI.

Anyway, I'm already working on a fix for that. Do you think it will be worth to do a patch release so that transformers CI doesn't have to wait for next release to be stable again ?

**Comment by sgugger** [comment]
I don't think it's serious enough to warrant a patch release by itself. But if you happen to do one for another reason, please include the fix in it.

Thanks!

**Comment by Wauplin** [comment]
Agreed !

**Comment by MFajcik** [comment]
transformers==4.43.3, I experienced the same issue. Are you sure the race condition is fixed?

It happened when loading llama 406B on 8 nodes (64 processes).
```
[rank0]: Traceback (most recent call last):                                                                           
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/runpy.py", line 197, in _run_mod
ule_as_main                                                                                                           
[rank0]:     return _run_code(code, main_globals, None,                                                               
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/runpy.py", line 87, in _run_code
[rank0]:     exec(code, run_globals)                                                                                  
[rank0]:   File "/scratch/project/open-30-35/ifajcik/lm-evaluation-harness/lm_eval/__main__.py", line 454, in <module>
[rank0]:     cli_evaluate()                                                                                           
[rank0]:   File "/scratch/project/open-30-35/ifajcik/lm-evaluation-harness/lm_eval/__main__.py", line 375, in cli_eval
uate                                                                                                                  
[rank0]:     results = evaluator.simple_evaluate(                                                                     
[rank0]:   File "/scratch/project/open-30-35/ifajcik/lm-evaluation-harness/lm_eval/utils.py", line 407, in _wrapper   
[rank0]:     return fn(*args, **kwargs)                                                                               
[rank0]:   File "/scratch/project/open-30-35/ifajcik/lm-evaluation-harness/lm_eval/evaluator.py", line 192, in simple_
evaluate                                                                                                              
[rank0]:     lm = lm_eval.api.registry.get_model(model).create_from_arg_string(                                       
[rank0]:   File "/scratch/project/open-30-35/ifajcik/lm-evaluation-harness/lm_eval/api/model.py", line 147, in create_
from_arg_string                                                                                                       
[rank0]:     return cls(**args, **args2)                                                                              
[rank0]:   File "/scratch/project/open-30-35/ifajcik/lm-evaluation-harness/lm_eval/models/vllm_causallms.py", line 109
, in __init__                                                                                                         
[rank0]:     self.model = LLM(**self.model_args)                                                                      
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/entrypoints/l
lm.py", line 175, in __init__                                                                                         
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(                                                            
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/engine/llm_en
gine.py", line 473, in from_engine_args                                                                               
[rank0]:     engine = cls(                                                                                            
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/engine/llm_en
gine.py", line 270, in __init__                                                                                       
[rank0]:     self.model_executor = executor_class(                                                                    
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/executor/dist
ributed_gpu_executor.py", line 25, in __init__                                                                        
[rank0]:     super().__init__(*args, **kwargs)                                                                        
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/executor/exec
utor_base.py", line 46, in __init__                                                                                   
[rank0]:     self._init_executor()                                                                                    
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/executor/ray_
gpu_executor.py", line 64, in _init_executor                                                                          
[rank0]:     self._init_workers_ray(placement_group)                                                                  
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/executor/ray_
gpu_executor.py", line 276, in _init_workers_ray                                                                      
[rank0]:     self._run_workers("load_model",                                                                          
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/executor/ray_
gpu_executor.py", line 420, in _run_workers                                                                           
[rank0]:     ray_worker_outputs = ray.get(ray_worker_outputs)                                                         
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/ray/_private/auto_
init_hook.py", line 21, in auto_init_wrapper                                                                          
[rank0]:     return fn(*args, **kwargs)                                                                               
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/ray/_private/clien
t_mode_hook.py", line 103, in wrapper                                                                        [33/1916]
[rank0]:     return func(*args, **kwargs)                                                                             
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/ray/_private/worke
r.py", line 2659, in get                                                                                              
[rank0]:     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)                           
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/ray/_private/worke
r.py", line 871, in get_objects                                                                                       
[rank0]:     raise value.as_instanceof_cause()                                                                        
[rank0]: ray.exceptions.RayTaskError(FileExistsError): ray::RayWorkerWrapper.execute_method() (pid=88846, ip=10.48.20.
21, actor_id=af4ea35bc9ae2d284435217a02000000, repr=<vllm.executor.ray_utils.RayWorkerWrapper object at 0x147f427c4f10
>)                                                                                                                    
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/worker/worker
_base.py", line 460, in execute_method                                                                                
[rank0]:     raise e                                                                                                  
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/worker/worker
_base.py", line 451, in execute_method                                                                                
[rank0]:     return executor(*args, **kwargs)                                                                         
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/worker/worker
.py", line 182, in load_model                                                                                         
[rank0]:     self.model_runner.load_model()                                                                           
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/worker/model_
runner.py", line 881, in load_model                                                                                   
[rank0]:     self.model = get_model(model_config=self.model_config,                                                   
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/model_executo
r/model_loader/__init__.py", line 19, in get_model                                                                    
[rank0]:     return loader.load_model(model_config=model_config,                                                      
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/model_executo
r/model_loader/loader.py", line 345, in load_model                                                                    
[rank0]:     self._get_weights_iterator(model_config.model,                                                           
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/model_executo
r/model_loader/loader.py", line 306, in _get_weights_iterator                                                         
[rank0]:     hf_folder, hf_weights_files, use_safetensors = self._prepare_weights(                                    
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/model_executo
r/model_loader/loader.py", line 261, in _prepare_weights                                                              
[rank0]:     hf_folder = download_weights_from_hf(
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/vllm/model_execut$r/model_loader/weight_utils.py", line 240, in download_weights_from_hf                                               
[rank0]:     hf_folder = snapshot_download(
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/huggingface_hub/u$ils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/huggingface_hub/_$napshot_download.py", line 294, in snapshot_download
[rank0]:     thread_map(
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/tqdm/contrib/conc$rrent.py", line 69, in thread_map
[rank0]:     return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)                                 
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/tqdm/contrib/conc$rrent.py", line 51, in _executor_map
[rank0]:     return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))                          
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/tqdm/std.py", lin$ 1169, in __iter__
[rank0]:     for obj in iterable:
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/concurrent/futures/_base.py", l$ne 608, in result_iterator
[rank0]:     yield fs.pop().result()
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/concurrent/futures/_base.py", l$ne 438, in result
[rank0]:     return self.__get_result()
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/concurrent/futures/_base.py", l$ne 390, in __get_result
[rank0]:     raise self._exception
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/concurrent/futures/thread.py", $ine 52, in run
[rank0]:     result = self.fn(*self.args, **self.kwargs)
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/huggingface_hub/_$napshot_download.py", line 268, in _inner_hf_hub_download
[rank0]:     return hf_hub_download(
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/huggingface_hub/u$ils/_validators.py", line 114, in _inner_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/huggingface_hub/f$le_download.py", line 1221, in hf_hub_download
[rank0]:     return _hf_hub_download_to_cache_dir(
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/huggingface_hub/f$le_download.py", line 1350, in _hf_hub_download_to_cache_dir                                                         
[rank0]:     _create_symlink(blob_path, pointer_path, new_blob=False)                                                
[rank0]:   File "/scratch/project/open-30-35/ifajcik/mamba/envs/harness/lib/python3.9/site-packages/huggingface_hub/f$le_download.py", line 915, in _create_symlink
[rank0]:     os.symlink(src_rel_or_abs, abs_dst)
[rank0]: FileExistsError: [Errno 17] File exists: '../../blobs/411a01184d84a4389daf854d282263ec6ff17325b7bd5b56c870e7$3de9ea2f9' -> '/home/ifajcik/data_scratch_new/hfhome/hub/models--meta-llama--Meta-Llama-3.1-405B-Instruct/snapshots/e$1d7495e96e12ce413fa2d3a56de1e0ce790dd0/model-00022-of-00191.safetensors' 
```

**Comment by MFajcik** [comment]
Sorry, I see there was a recent fix on this issue again.
Link here, if anyone else finds this thread first.

https://github.com/huggingface/huggingface_hub/pull/2534
