### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by mikwee** [huggingface/huggingface_hub#1209]
### Describe the bug

When I try to log into my account with the token via `huggingface-cli login`, I get this error:
```
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 387: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\Scripts\huggingface-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\huggingface_cli.py", line 47, in main
    service.run()
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\commands\user.py", line 117, in run
    login()
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\_login.py", line 91, in login
    interpreter_login()
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\_login.py", line 137, in interpreter_login
    _login(token=token, add_to_git_credential=add_to_git_credential)
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\_login.py", line 231, in _login
    if _is_git_credential_helper_configured():
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\_login.py", line 251, in _is_git_credential_helper_configured
    helpers = list_credential_helpers()
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_git_credential.py", line 44, in list_credential_helpers
    for line in output.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'
```
Also, when using `huggingface-cli env`, I got this error. I dunno if it's related, but here it is anyway:
```
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1494, in _readerthread
    buffer.append(fh.read())
  File "C:\Users\mikwee\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 387: invalid continuation byte
```

### Reproduction

The commands I've used:
```
git clone https://github.com/harishanand95/diffusers.git
cd diffusers && git checkout dml && pip install -e .
pip install transformers ftfy scipy
pip install ort_nightly_directml-1.13.0.dev20220901005-cp310-cp310-win_amd64.whl
cd ./diffusers/examples/inference
huggingface-cli login
```

### System info

```shell
- huggingface_hub version: 0.11.0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.4
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\mikwee\.huggingface\token
- Has saved token ?: False
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.13.0
- Jinja2: N/A
- Graphviz: N/A
- Pydot: N/A
```

**Comment by Wauplin** [comment]
Hi @mikwee thanks for reporting and sorry you are getting this issue.

Do you happen to know why the exception is raised in a child Thread instead of the main thread ? I have been able to reproduce a similar issue locally but `subprocess.run` shouldn't be running in a thread (at least not by default for what I thought). Also you have been able to dump your machine details. Does it mean that `huggingface-cli env` raises an error but is still able to print the debug information ?

Also, could you copy-paste me the output when you run `git config --list` (potentially remove if there are sensitive information in it) ? That would help investigating.

**Comment by mikwee** [comment]
Also note: I tried this again, and before the error it told me my token was valid... which is good, but not really useful if I can't log into my account. I have no idea if this matters, but more info is always good.

**Comment by Wauplin** [comment]
@mikwee I have created [a PR](https://github.com/huggingface/huggingface_hub/pull/1218) to try to fix your issue.

Could you install `huggingface_hub` from this branch and test if error is still happening ?

```sh
# Uninstall first, just in case
pip uninstall huggingface_hub

# Install from fix branch
pip install git+https://github.com/huggingface/huggingface_hub.git@1209-fix-subprocess-encoding-issues

# Test !
huggingface-cli login
huggingface-cli env
```

Hope this will fix the issue. Please let me know if it's the case and I'll merge the PR :)

**Comment by mikwee** [comment]
It works! Thank you so much!

And in case you wanted to know:
```
- huggingface_hub version: 0.12.0.dev0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.4
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\mikwee\.huggingface\token
- Has saved token ?: True
- Who am I ?: mikwee
- Configured git credential helpers: helper-selector
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.13.0
- Jinja2: N/A
- Graphviz: N/A
- Pydot: N/A
```
