### ISSUE TITLE
500 Server Error when calling ModelSearchArguments()

### ISSUE THREAD

**Issue by lstein** [huggingface/huggingface_hub#1211]
### Describe the bug

```
import huggingface_hub
model_args = ModelSearchArguments()
```
output:
```
Traceback (most recent call last):
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 239, in hf_raise_for_status
    response.raise_for_status()
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 514, in __init__
    self._process_models()
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 520, in _process_models
    models = self._api.list_models()
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 152, in inner_f
    list_value = f(*args, **kwargs)
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 817, in list_models
    items = [ModelInfo(**x) for x in data]
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/hf_api.py", line 817, in <listcomp>
    items = [ModelInfo(**x) for x in data]
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/utils/_pagination.py", line 39, in paginate
    hf_raise_for_status(r)
  File "/home/lstein/miniconda3/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 280, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models (Request ID: Nzy8wOzhXJx-Qa473hRAR)

Internal Error - We're working hard to fix that as soon as possible!
```

### Reproduction

See Above

### Logs

```shell
See above
```

### System info

```shell
- huggingface_hub version: 0.11.0
- Platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.31
- Python version: 3.9.7
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/lstein/.huggingface/token
- Has saved token ?: True
- Who am I ?: LincolnStein
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.13.0+git7c98e70
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
```

**Comment by Wauplin** [comment]
Hi @lstein , thanks for reporting. That was due to a server-side issue over the weekend. This is has been fixed today :)
