### ISSUE TITLE
Caching error when using from_pretrained

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#1305]
### Describe the bug

When loading an image processor from the 🤗 Transformers library using the `from_pretrained` method in [this Space](https://huggingface.co/spaces/nielsr/swin2sr-image-super-resolution), I get the following error:

```
Traceback (most recent call last):
  File "app.py", line 8, in <module>
    processor = AutoImageProcessor.from_pretrained("caidas/swin2SR-classical-sr-x2-64")
  File "/home/user/.local/lib/python3.8/site-packages/transformers/models/auto/image_processing_auto.py", line 307, in from_pretrained
    config_dict, _ = ImageProcessingMixin.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 257, in get_image_processor_dict
    resolved_image_processor_file = cached_file(
  File "/home/user/.local/lib/python3.8/site-packages/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1150, in hf_hub_download
    with open(ref_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/huggingface/hub/models--caidas--swin2SR-classical-sr-x2-64/refs/main'
```

### Reproduction

I'm not able to reproduce it locally. The following works for me locally:
```
from transformers import AutoImageProcessor

processor = AutoImageProcessor.from_pretrained("caidas/swin2SR-classical-sr-x2-64")
```

Also tried restarting and factory rebooting the Space, but the same issue occurs. 

### Logs

```shell
/
```

### System info

Spaces environment, Gradio backend

**Comment by NielsRogge** [comment]
Update: the Space works as intended now: https://huggingface.co/spaces/nielsr/swin2sr-image-super-resolution.

I think the issue occurred when updating the Transformers version in the requirements.txt from the PyPi version to the main branch.

**Comment by Wauplin** [comment]
Ok. I'm closing this issue then. Should have been fixed by the PR.
