### ISSUE TITLE
Uploading an image to a HF Dataset sometimes crashes Gradio

### ISSUE THREAD

**Issue by lakshman111** [huggingface/huggingface_hub#1373]
### Describe the bug

After a user submits a request on https://www.virtualstaging.art/, I'm logging their image to a HuggingFace dataset with:

`HF_API_TOKEN = os.environ.get("HF_API_TOKEN")
hf_writer = gr.HuggingFaceDatasetSaver(HF_API_TOKEN, "virtual_staging_attempts")

demo = gr.Interface(
    fn=make_new_style,
    allow_flagging="auto",
    flagging_callback=hf_writer,
...

`

Sometimes, my script powering Gradio will crash with the following error ("anthony" is my conda environment):

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/envs/anthony/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/envs/anthony/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/envs/anthony/lib/python3.8/site-packages/huggingface_hub/repository.py", line 382, in output_progress
    state, file_progress, byte_progress, filename = line.split()
ValueError: too many values to unpack (expected 4)
remote: Scanning LFS files of refs/heads/main for validity...
remote: LFS file scan complete.
To https://huggingface.co/datasets/lakshman111/virtual_staging_attempts
   13c7d10..e312b49  main -> main"

### Reproduction

I'm unable to reproduce as the issue does not occur every time the user submits a request (I know, the worst kind of bug...)

### Logs

```shell
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/envs/anthony/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/envs/anthony/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/envs/anthony/lib/python3.8/site-packages/huggingface_hub/repository.py", line 382, in output_progress
    state, file_progress, byte_progress, filename = line.split()
ValueError: too many values to unpack (expected 4)
remote: Scanning LFS files of refs/heads/main for validity...
remote: LFS file scan complete.
To https://huggingface.co/datasets/lakshman111/virtual_staging_attempts
   13c7d10..e312b49  main -> main"
```

### System info

```shell
- huggingface_hub version: 0.12.1
- Platform: Linux-5.15.0-48-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers:
- FastAI: 2.7.11
- Tensorflow: N/A
- Torch: 1.13.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /root/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_HUB_OFFLINE: False
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_HUB_DISABLE_PROGRESS_BARS: True
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @lakshman111 thanks for reporting this. I think it will be quite hard to reproduce/fix but we could at least write a workaround so that at least when this ValueError is raised we print the breaking `line` variable before raising.
```
state, file_progress, byte_progress, filename = line.split()
ValueError: too many values to unpack (expected 4)
```

In general, I quickly had a look to the [Gradio implementation](https://github.com/gradio-app/gradio/blob/d8023d455f2e86e2a9c6e463fe43b84583095bc4/gradio/flagging.py#L287) and it seems to be a bit outdated (though not being wrong). I'll have a look at it early next week to use the HTTP methods (`hf_hub_download` and `upload_file`) instead of the `Repository` object. It should make things more robust and errors more explicit. cc @abidlabs.

**Comment by lakshman111** [comment]
Hi @Wauplin thank you for taking a look.  Printing the "line" variable would be helpful for me to debug when it occurs again!

I looked at the class you linked in the [Gradio implementation](https://github.com/gradio-app/gradio/blob/d8023d455f2e86e2a9c6e463fe43b84583095bc4/gradio/flagging.py#L287) and I believe that is referring to, allow_flagging="manual" (I'm Iooking at the comment describing the class), but I'm doing allow_flagging="auto" to log all images users are submitting.  Thought I'd flag (no pun intended) incase that's important to note.

Regarding your "**EDIT**" comment: I think you are saying that I may experience this error when I have concurrent users.  I'll test that out!

**Comment by lakshman111** [comment]
I tried concurrent calls and got the following error.  Interestingly, the main thread continued to work and I could make subsequent calls after.

`Traceback (most recent call last):
  File "/usr/local/envs/laura/lib/python3.8/site-packages/huggingface_hub/repository.py", line 1072, in git_commit
    result = run_subprocess(
  File "/usr/local/envs/laura/lib/python3.8/site-packages/huggingface_hub/utils/_subprocess.py", line 61, in run_subprocess
    return subprocess.run(
  File "/usr/local/envs/laura/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'commit', '-v', '-m', 'Flagged sample #109']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/laura/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/envs/laura/lib/python3.8/site-packages/gradio/blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "/usr/local/envs/laura/lib/python3.8/site-packages/gradio/blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/envs/laura/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/envs/laura/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/envs/laura/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/envs/laura/lib/python3.8/site-packages/gradio/flagging.py", line 587, in __call__
    self.flagging_callback.flag(list(flag_data), flag_option=self.flag_option)
  File "/usr/local/envs/laura/lib/python3.8/site-packages/gradio/flagging.py", line 410, in flag
    self.repo.push_to_hub(commit_message="Flagged sample #{}".format(line_count))
  File "/usr/local/envs/laura/lib/python3.8/site-packages/huggingface_hub/repository.py", line 1367, in push_to_hub
    self.git_commit(commit_message)
  File "/usr/local/envs/laura/lib/python3.8/site-packages/huggingface_hub/repository.py", line 1080, in git_commit
    raise EnvironmentError(exc.stdout)
OSError: On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

To https://huggingface.co/datasets/lakshman111/virtual_staging_attempts
   bdfd84b..3e1bbaf  main -> main`

**Comment by lakshman111** [comment]
@Wauplin I now see the error on start of my script (before any user has interacted with the UI):

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/envs/laura/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/envs/laura/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/envs/laura/lib/python3.8/site-packages/huggingface_hub/repository.py", line 382, in output_progress
    state, file_progress, byte_progress, filename = line.split()
ValueError: too many values to unpack (expected 4)

**Comment by Wauplin** [comment]
@lakshman111 Did you change something compared to before? Especially `gradio` or `huggingface_hub` versions?

If you can, it would be nice to upgrade your `huggingface_hub` version. I made a release yesterday (0.13.0) including a small tweak to better debug this issue.

**Comment by lakshman111** [comment]
@Wauplin I updated to the latest gradio and huggingface_hub versions earlier today right before my last post.  I thought it was strange when nothing new was printed with the same error, since your tweak should have printed something...

More info: the error does not occur when I run the same script without `huggingface_hub`.

**Comment by Wauplin** [comment]
Fixed by https://github.com/gradio-app/gradio/pull/3973. I'm closing this issue.
