### ISSUE TITLE
OSError: Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility while importing  RobertaTokenizer.from_pretrained(model_name)

### ISSUE THREAD

**Issue by bhaveshk1502** [huggingface/huggingface_hub#1417]
here is the complete error 
2023-03-29 18:07:58.935067: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-29 18:07:58.935251: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2023-03-29 18:07:58.935280: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Calculating style of predictions
Traceback (most recent call last):
  File "/content/fairseq/metric.py", line 161, in <module>
    accuracy_by_sent = classify_preds(args, preds)
  File "/content/fairseq/metric.py", line 33, in classify_preds
    tokenizer = RobertaTokenizer.from_pretrained(model_name)
  File "/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py", line 1692, in from_pretrained
    resolved_vocab_files[file_id] = cached_path(
  File "/usr/local/lib/python3.9/dist-packages/transformers/file_utils.py", line 1402, in cached_path
    output_path = get_from_cache(
  File "/usr/local/lib/python3.9/dist-packages/transformers/file_utils.py", line 1580, in get_from_cache
    raise OSError(
OSError: Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility.

got this error in colab, transformers version is transformers==4.11.1

**Comment by Wauplin** [comment]
@bhaveshk1502  Actually transformers 4.11 is very outdated (dates back to Sept 2021). Latest version is transformers 4.27. The issue will most likely be gone if you upgrade it:

```
pip install -U transformers
```
