### ISSUE TITLE
Can not run huggingface-cli login

### ISSUE THREAD

**Issue by phongnhhn92** [huggingface/huggingface_hub#1471]
### Describe the bug

Hi,

I have been trying to run `huggingface-cli login` but I have this error:

```
[phongngu@r15g02 huggingface_hub]$ huggingface-cli login
Traceback (most recent call last):
  File "/users/phongngu/.local/bin/huggingface-cli", line 33, in <module>
    sys.exit(load_entry_point('huggingface-hub', 'console_scripts', 'huggingface-cli')())
  File "/users/phongngu/.local/bin/huggingface-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/commands/huggingface_cli.py", line 18, in <module>
    from huggingface_hub.commands.delete_cache import DeleteCacheCommand
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/commands/delete_cache.py", line 64, in <module>
    from ..utils import CachedRepoInfo, CachedRevisionInfo, HFCacheInfo, scan_cache_dir
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/utils/__init__.py", line 18, in <module>
    from . import tqdm as _tqdm  # _tqdm is the module
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/utils/tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm'
```

### Reproduction

I follow the installation instruction to install from source: 
```
# First, clone repo locally
git clone https://github.com/huggingface/huggingface_hub.git

# Then, install with -e flag
cd huggingface_hub
pip install -e .
```

Then I run: `huggingface-cli login`

### Logs

```shell
[phongngu@r15g02 huggingface_hub]$ huggingface-cli login
Traceback (most recent call last):
  File "/users/phongngu/.local/bin/huggingface-cli", line 33, in <module>
    sys.exit(load_entry_point('huggingface-hub', 'console_scripts', 'huggingface-cli')())
  File "/users/phongngu/.local/bin/huggingface-cli", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/commands/huggingface_cli.py", line 18, in <module>
    from huggingface_hub.commands.delete_cache import DeleteCacheCommand
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/commands/delete_cache.py", line 64, in <module>
    from ..utils import CachedRepoInfo, CachedRevisionInfo, HFCacheInfo, scan_cache_dir
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/utils/__init__.py", line 18, in <module>
    from . import tqdm as _tqdm  # _tqdm is the module
  File "/users/phongngu/.local/lib/python3.9/site-packages/huggingface_hub/utils/tqdm.py", line 63, in <module>
    from tqdm.auto import tqdm as old_tqdm
ModuleNotFoundError: No module named 'tqdm'
```

### System info

```shell
- huggingface_hub version: 0.12.0
- Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
- Python version: 3.9.16
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/phong/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: phongnhhn92
- Configured git credential helpers: cache
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.13.0
- Jinja2: N/A
- Graphviz: N/A
- Pydot: 1.4.2
- Pillow: 9.3.0
- hf_transfer: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/phong/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/phong/.cache/huggingface/assets
- HF_HUB_OFFLINE: False
- HF_TOKEN_PATH: /home/phong/.cache/huggingface/token
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Hi @phongnhhn92 for some reason, it seems that you are running huggingface_hub on an older version which is weird given the fact that you install it from the source. Could you do:

```sh
cd huggingface_hub
git pull 
pip uninstall huggingface_hub
pip install -e .
```

And then retry ? (Both `huggingface-cli login` and `huggingface-cli env`)

**Comment by Wauplin** [comment]
No news since 1 month => I'm closing this issue. Please reopen if needed.
