### ISSUE TITLE
Allow snapshot_download to retry on requests.exceptions.ConnectionError

### ISSUE THREAD

**Issue by thundergolfer** [huggingface/huggingface_hub#1542]
**Is your feature request related to a problem? Please describe.**

When downloading large files using **`snapshot_download`**, a transient `Read timed out` exception crashes the process and there's no in-built retry method. Some retrying wrapper code could be written, but I'm suggesting that this functionality would be useful as a parameter to the `snapshot_download` function. 

**Describe the solution you'd like**

A parameter which allows setting a (basic) retry policy for network-related exceptions (e.g. `requests.exceptions.ConnectionError`). 

**Describe alternatives you've considered**

Writing some wrapper code around the [`snapshot_download`](https://huggingface.co/docs/huggingface_hub/v0.16.2/en/package_reference/file_download#huggingface_hub.snapshot_download.resume_download) call that does the retrying, passing in `resume_download=True` to hopefully continue on from where the network exception occurred 🤞. 

**Additional context**

The downloading Python process is typically running in an AWS `g5.12xlarge` instance in us-east-1 or us-east-2. Network bandwidth or stability should be excellent. (Not running the code in Antarctica or anything like that 😄) 

_Full logs of exception mentioned above:_ 

```Fetching 9 files:  22%|██▏       | 2/9 [02:44<09:36, 82.36s/it]
02:16, 88.4MB/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 814, in _raw_read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 799, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.10/http/client.py", line 465, in read
    s = self.fp.read(amt)
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 940, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 879, in read
    data = self._raw_read(amt)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 813, in _raw_read
    with self._error_catcher():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/response.py", line 715, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 330, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 403, in call_function_sync
    res = fun(*args, **kwargs)
  File "/root/bloomz-q4.py", line 19, in download_model
    snapshot_download(MODEL_NAME, local_dir=IMG_MODEL_DIR)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 235, in snapshot_download
    thread_map(
  File "/usr/local/lib/python3.10/dist-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/_snapshot_download.py", line 211, in _inner_hf_hub_download
    return hf_hub_download(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py", line 541, in http_get
    for chunk in r.iter_content(chunk_size=10 * 1024 * 1024):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 822, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading bloomz-splitab:  75%|███████▌  | 36.3G/48.3G [02:41<00:53, 224MB/s] 
```

**Comment by Wauplin** [comment]
Hi @thundergolfer thanks for reporting and sorry for the late answer. First of all, we published a patch release last friday ([v0.16.4](https://github.com/huggingface/huggingface_hub/releases/tag/v0.16.4)) that should solve the `Read timed out` issues when downloading. As you said, on a `g5.12xlarge` this should never happen but we had a slight bug in our implementation that made `requests.Session` object duplicated, hence causing unexpected errors  :grimacing:. I hope it will solve the issue for you as well even though I know it's most likely non-reproducible.

I'm not a fan of adding a new parameter to `snapshot_download` to be honest. At the moment we already have a retry strategy for `Timeout` and `ProxyError`. Read timeout are a bit different (`ConnectionError: Read timed out.` is not processed as a `Timeout` error - see https://github.com/psf/requests/issues/5430). The retry strategy in the case of a Read timeout would be a bit different because the download might have already started and we don't want to download again bytes that are already stored. In the end, the "best" solution might just be:

```py
import time
from huggingface_hub import snapshot_download
from requests import ConnectionError

while True:
    try:
        snapshot_path =  snapshot_download(..., resume_download=True)
        break
    except ConnectionError as e:
        print(f"ConnectionError: {e}. Retrying in 1s...")
        time.sleep(1)
```

Since it's quite some boilerplate code, we might integrate it directly in `huggingface_hub` in the future. However, I'd rather wait for more feedback before doing so. Hopefully read timeouts should be very rare now that we pushed a fix.

**Comment by thundergolfer** [comment]
Thanks for the reply. Understand your concerns around retrying on `Read timed out`. We'll try the patch.

**Comment by chukarsten** [comment]
Running v0.16.4, I still seem to be running into the Read timed out. issue with flan-t5-xl.  I am not using snapshot_download, though, I am using `from_pretrained()`

```
model = AutoModelForSeq2SeqLM.from_pretrained(
            model_choice,
            load_in_8bit=True,
            device_map="auto",
            quantization_config=quantization_config,
            resume_download=True, # Had to put this in for the XL model end to end integration test.
        )
```

**Comment by Wauplin** [comment]
@abeiler7 Looks like a network shortage that happened during the download. It seems to be different than the "duplicate Session" issue I initially mentioned in https://github.com/huggingface/huggingface_hub/issues/1542#issuecomment-1630465844. Possibly a retry should be enough. Will look into integrating something in `huggingface_hub` if it keeps happening... :confused: 

(in any case, not a `transformers` issue I'd say)

**Comment by thundergolfer** [comment]
Thanks fro your work @Wauplin 🙏

**Comment by chukarsten** [comment]
Yep, thank you.  Will try this with the next hfh release

**Comment by itscheems** [comment]
`resume_download` is deprecated and will be removed in version 1.0.0.
You can see it from the source code: [Link -> file_download.py](https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/file_download.py#L942)

```python
if resume_download is not None:
    warnings.warn(
        "`resume_download` is deprecated and will be removed in version 1.0.0. "
        "Downloads always resume when possible. "
        "If you want to force a new download, use `force_download=True`.",
        FutureWarning,
    )
```
