### ISSUE TITLE
Wrong error to handle Paused or Scaled to Zero endpoints.

### ISSUE THREAD

**Issue by viniciusarruda** [huggingface/huggingface_hub#1605]
### Describe the bug

What I want:

1. When the [endpoint](https://ui.endpoints.huggingface.co/) is paused and a request is made, I want to handle the raised error correctly.
2. When the [endpoint](https://ui.endpoints.huggingface.co/) is Scaled to Zero and a request is made when no replica is running (due to idle time), I want to handle the raised error correctly.

Looking the [code](https://github.com/huggingface/huggingface_hub/blob/b9901bf71839850c10ea42162c69aecabc96a46b/src/huggingface_hub/inference/_client.py#L243C40-L243C40), it seems to only handle error `503`, by retrying. However, I'm getting `MaxRetryError` for the first scenario and `HTTPError: 502` for the second one.

### Reproduction

Set the endpoints at [https://ui.endpoints.huggingface.co/](https://ui.endpoints.huggingface.co/):

First scenario:
![image](https://github.com/huggingface/huggingface_hub/assets/14860534/c8e74400-7fd7-45dd-bc14-a5a0c9d5e8df)

Second scenario:
![image](https://github.com/huggingface/huggingface_hub/assets/14860534/1fd3506b-85cb-47c9-a85b-28ddee4ae011)

Then, make a call with `InferenceClient` calling `text_generation()`.

#### First scenario

```powershell
Traceback (most recent call last):
  File "<omitted>\.venv\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "<omitted>\.venv\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "<omitted>\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<omitted>\.venv\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "<omitted>\.venv\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "<omitted>\.venv\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "<omitted>\.venv\lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "<omitted>\.venv\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "<omitted>\.venv\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x00000262E1085CC0>: Failed to resolve '<omitted>.us-east-1.aws.endpoints.huggingface.cloud' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<omitted>\.venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "<omitted>\.venv\lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "<omitted>\.venv\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='<omitted>.us-east-1.aws.endpoints.huggingface.cloud', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000262E1085CC0>: Failed to resolve '<omitted>.us-east-1.aws.endpoints.huggingface.cloud' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<omitted>\code\streamlit_app.py", line 298, in <module>
    main()
  <omitted-lines>
  File "<omitted>\code\.\chat_completion_wrapper\hf_chat_completion_wrapper.py", line 96, in __call__
    response = self.client.text_generation(formatted_messages, stream=False, details=True, **params)
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\inference\_client.py", line 1041, in text_generation
    bytes_output = self.post(json=payload, model=model, task="text-generation", stream=stream)  # type: ignore
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\inference\_client.py", line 207, in post
    response = get_session().post(
  File "<omitted>\.venv\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "<omitted>\.venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "<omitted>\.venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "<omitted>\.venv\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'<omitted>.us-east-1.aws.endpoints.huggingface.cloud\', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000262E1085CC0>: Failed to resolve \'<omitted>.us-east-1.aws.endpoints.huggingface.cloud\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: <omitted>)')
```

#### Second scenario

```powershell
Traceback (most recent call last):
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "<omitted>\.venv\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://<omitted>.us-east-1.aws.endpoints.huggingface.cloud/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<omitted>\code\streamlit_app.py", line 298, in <module>
    main()
  <omitted-lines>
  File "<omitted>\code\.\chat_completion_wrapper\hf_chat_completion_wrapper.py", line 96, in __call__
    response = self.client.text_generation(formatted_messages, stream=False, details=True, **params)
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\inference\_client.py", line 1065, in text_generation
    raise_text_generation_error(e)
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\inference\_text_generation.py", line 479, in raise_text_generation_error
    raise http_error
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\inference\_client.py", line 1041, in text_generation
    bytes_output = self.post(json=payload, model=model, task="text-generation", stream=stream)  # type: ignore
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\inference\_client.py", line 221, in post
    hf_raise_for_status(response)
  File "<omitted>\.venv\lib\site-packages\huggingface_hub\utils\_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 502 Server Error: Bad Gateway for url: https://<omitted>.us-east-1.aws.endpoints.huggingface.cloud/ (Request ID: <omitted>)
```

### System info

```shell
- huggingface_hub version: 0.16.4
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.9
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\vinicius.arruda\.cache\huggingface\token
- Has saved token ?: True
- Who am I ?: viniciusarruda
- Configured git credential helpers: manager-core
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.25.0
- pydantic: 1.10.9
- aiohttp: 3.8.4
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: C:\Users\vinicius.arruda\.cache\huggingface\hub
- HUGGINGFACE_ASSETS_CACHE: C:\Users\vinicius.arruda\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\vinicius.arruda\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False

{'huggingface_hub version': '0.16.4', 'Platform': 'Windows-10-10.0.22621-SP0', 'Python version': '3.10.9', 'Running in iPython ?': 'No', 'Running in notebook ?': 'No', 'Running in Google Colab ?': 'No', 'Token path ?': WindowsPath('C:/Users/vinicius.arruda/.cache/huggingface/token'), 'Has saved token ?': True, 'Who am I ?': 'viniciusarruda', 'Configured git credential helpers': 'manager-core', 'FastAI': 'N/A', 'Tensorflow': 'N/A', 'Torch': '2.0.1', 'Jinja2': '3.1.2', 'Graphviz': 'N/A', 'Pydot': 'N/A', 'Pillow': '9.5.0', 'hf_transfer': 'N/A', 'gradio': 'N/A', 'tensorboard': 'N/A', 'numpy': '1.25.0', 'pydantic': '1.10.9', 'aiohttp': '3.8.4', 'ENDPOINT': 'https://huggingface.co', 'HUGGINGFACE_HUB_CACHE': 'C:\\Users\\vinicius.arruda\\.cache\\huggingface\\hub', 'HUGGINGFACE_ASSETS_CACHE': 'C:\\Users\\vinicius.arruda\\.cache\\huggingface\\assets', 'HF_TOKEN_PATH': 'C:\\Users\\vinicius.arruda\\.cache\\huggingface\\token', 'HF_HUB_OFFLINE': False, 'HF_HUB_DISABLE_TELEMETRY': False, 'HF_HUB_DISABLE_PROGRESS_BARS': None, 'HF_HUB_DISABLE_SYMLINKS_WARNING': False, 'HF_HUB_DISABLE_EXPERIMENTAL_WARNING': False, 'HF_HUB_DISABLE_IMPLICIT_TOKEN': False, 'HF_HUB_ENABLE_HF_TRANSFER': False}
```

**Comment by julien-c** [comment]
cc @philschmid maybe

**Comment by philschmid** [comment]
cc @McPatate @co42

**Comment by McPatate** [comment]
Hello @viniciusarruda, what do you mean by
> I want to handle the raised error correctly
?

The errors you are seeing are the correct errors. Are you saying that you want a custom error on top, e.g. `PausedEndpointError`?

**Comment by viniciusarruda** [comment]
Hi @McPatate, here is what I'm doing:

```python
try:
    response = self.client.text_generation(formatted_messages, stream=False, details=True, **params)
except HfHubHTTPError as e:
    if e.response.status_code == 502:
        raise LoadingModelError from e
    raise
except requests.exceptions.ConnectionError as e:
    raise UnknownEndpointError from e
```

In my application, I need to check whether the model is not available (paused) or if is available but is loading (when setting the scale to zero). This is a feedback given to my front-end application, showing to the user something like "hey, wait some minutes, the model is loading".

The problem is that I'm handling every HfHubHTTPError  with status code 502 as a "LoadingModelError" and all ConnectionError as "UnknownEndpointError", which might not be true.

**Comment by McPatate** [comment]
I'd advise checking the state of your endpoint using [`get_endpoint`](https://api.endpoints.huggingface.cloud/#/v2%3A%3Aendpoint/get_endpoint).

You are correct that 502 errors can mean something else than "the model is scaling up". Same goes for paused, the `ConnectionError` can mean something else than pause.

**Comment by viniciusarruda** [comment]
Ok, it worked. 
However, it is not an elegant solution IMO. 
I'm using `huggingface_hub.InferenceClient`, but to check this errors I need to use `requests`.
In addition to performing another endpoint call, I have to use another approach.

What I'm doing now:

```python
def _check_endpoint_status(self) -> tuple[int, str]:
    headers = {
        "Authorization": f"Bearer {self.token}",
        "Content-Type": "application/json",
    }

    response = requests.get(
        f"https://api.endpoints.huggingface.cloud/v2/endpoint/{self.namespace}/{self.name}", headers=headers
    )

    return response.status_code, None if response.status_code != 200 else response.json()["status"]["state"]
```


```python
try:
    response = self.client.text_generation(formatted_messages, stream=False, details=True, **params)
except Exception as e:
    status_code, endpoint_state = self._check_endpoint_status()
    if status_code == 200:
        # endpoint_state: str -> pending, initializing, updating, updateFailed, running, paused, failed, scaledToZero
        if endpoint_state == "paused":
            # renamed UnknownEndpointError  to DisabledEndpointError
            raise DisabledEndpointError from e
        elif endpoint_state in ["scaledToZero", "initializing"]:
            raise LoadingModelError from e
    raise
```

**Comment by StephenHodgson** [comment]
+1 to subscribe to updates to this.

I'm also having issues when checking if endpoint is ready for requests, instead just getting 500 error code

**Comment by StephenHodgson** [comment]
Seems like we might have to wait for this: https://github.com/huggingface/huggingface_hub/issues/1541

**Comment by Wauplin** [comment]
Thanks for the heads up @viniciusarruda and @StephenHodgson. Implementing https://github.com/huggingface/huggingface_hub/issues/1541 properly is the way to go yes. The month of August has being slower in term of development but you can except this issue to be implemented/release in the coming weeks. In the meantime, it's best to use `requests` directly.

**Comment by Wauplin** [comment]
Incoming... :eyes: https://github.com/huggingface/huggingface_hub/pull/1779

**Comment by Wauplin** [comment]
> Ok, it worked.
However, it is not an elegant solution IMO.
I'm using huggingface_hub.InferenceClient, but to check this errors I need to use requests.

> I'm also having issues when checking if endpoint is ready for requests, instead just getting 502 error code

```py
>>> from huggingface_hub import get_inference_endpoint

# Get endpoint info
>>> endpoint = get_inference_endpoint(name=...)
>>> endpoint
InferenceEndpoint(name=..., namespace=..., repository=..., status='paused', url=None)

# Resume endpoint + wait until running
>>> endpoint.resume().wait()
InferenceEndpoint(name=..., namespace=..., repository=..., status='running', url="https://...")

# Run inference
>>> endpoint.client  # InferenceClient instance with token + url already set
>>> endpoint.client.text_generation(...)

# Pause again
>>> endpoint.pause()
```

PR has been merged so you can already use it if you [install from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source). Otherwise we are planning `v0.19.0` to be released soon (end of this week or beginning of next one).
