### ISSUE TITLE
huggingface-cli login: ConnectionError 104

### ISSUE THREAD

**Issue by adarshxs** [huggingface/huggingface_hub#1633]
### Describe the bug

```
Token:

Add token as git credential? (Y/n) n

Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen

    httplib_response = self._make_request(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request

    self._validate_conn(conn)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn

    conn.connect()

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect

    self.sock = ssl_wrap_socket(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket

    return context.wrap_socket(sock, server_hostname=server_hostname)

  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket

    return self.sslsocket_class._create(

  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create

    self.do_handshake()

  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake

    self._sslobj.do_handshake()

ConnectionResetError: [Errno 104] Connection reset by peer



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen

    retries = retries.increment(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise

    raise value.with_traceback(tb)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen

    httplib_response = self._make_request(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request

    self._validate_conn(conn)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn

    conn.connect()

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect

    self.sock = ssl_wrap_socket(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket

    return context.wrap_socket(sock, server_hostname=server_hostname)

  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket

    return self.sslsocket_class._create(

  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create

    self.do_handshake()

  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake

    self._sslobj.do_handshake()

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/opt/conda/bin/huggingface-cli", line 8, in <module>

    sys.exit(main())

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/commands/huggingface_cli.py", line 45, in main

    service.run()

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/commands/user.py", line 101, in run

    login(token=self.args.token, add_to_git_credential=self.args.add_to_git_credential)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/_login.py", line 100, in login

    interpreter_login(new_session=new_session, write_permission=write_permission)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/_login.py", line 164, in interpreter_login

    _login(token=token, add_to_git_credential=add_to_git_credential, write_permission=write_permission)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/_login.py", line 273, in _login

    permission = get_token_permission(token)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 958, in get_token_permission

    return self.whoami(token=token)["auth"]["accessToken"]["role"]

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn

    return fn(*args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 925, in whoami

    r = get_session().get(

  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 543, in get

    return self.request('GET', url, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 530, in request

    resp = self.send(prep, **send_kwargs)

  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 643, in send

    r = adapter.send(request, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send

    return super().send(request, *args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 498, in send

    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 89b12fd1-6f6e-48ef-b743-5dddf31f72d8)')

root@ee39b0416444:/workspace# huggingface-cli whomai

usage: huggingface-cli <command> [<args>]

huggingface-cli: error: invalid choice: 'whomai' (choose from 'env', 'login', 'whoami', 'logout', 'repo', 'lfs-enable-largefiles', 'lfs-multipart-upload', 'scan-cache', 'delete-cache')

root@ee39b0416444:/workspace# huggingface-cli whoami

Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen

    httplib_response = self._make_request(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request

    self._validate_conn(conn)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn

    conn.connect()

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect

    self.sock = ssl_wrap_socket(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket

    return context.wrap_socket(sock, server_hostname=server_hostname)

  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket

    return self.sslsocket_class._create(

  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create

    self.do_handshake()

  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake

    self._sslobj.do_handshake()

ConnectionResetError: [Errno 104] Connection reset by peer



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 439, in send

    resp = conn.urlopen(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen

    retries = retries.increment(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment

    raise six.reraise(type(error), error, _stacktrace)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise

    raise value.with_traceback(tb)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen

    httplib_response = self._make_request(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request

    self._validate_conn(conn)

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn

    conn.connect()

  File "/opt/conda/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect

    self.sock = ssl_wrap_socket(

  File "/opt/conda/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket

    return context.wrap_socket(sock, server_hostname=server_hostname)

  File "/opt/conda/lib/python3.8/ssl.py", line 500, in wrap_socket

    return self.sslsocket_class._create(

  File "/opt/conda/lib/python3.8/ssl.py", line 1040, in _create

    self.do_handshake()

  File "/opt/conda/lib/python3.8/ssl.py", line 1309, in do_handshake

    self._sslobj.do_handshake()

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/opt/conda/bin/huggingface-cli", line 8, in <module>

    sys.exit(main())

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/commands/huggingface_cli.py", line 45, in main

    service.run()

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/commands/user.py", line 116, in run

    info = self._api.whoami(token)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn

    return fn(*args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/hf_api.py", line 925, in whoami

    r = get_session().get(

  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 543, in get

    return self.request('GET', url, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 530, in request

    resp = self.send(prep, **send_kwargs)

  File "/opt/conda/lib/python3.8/site-packages/requests/sessions.py", line 643, in send

    r = adapter.send(request, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 63, in send

    return super().send(request, *args, **kwargs)

  File "/opt/conda/lib/python3.8/site-packages/requests/adapters.py", line 498, in send

    raise ConnectionError(err, request=request)

requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: c664da84-a6d1-4ed0-b2ee-e81bbc155037)')
```

### System info

```shell
huggingface_hub version: 0.16.4
Platform: Linux-5.4.0-72-generic-x86_64-with-glibc2.29
Python version: 3.8.10
Running in iPython: No
Running in notebook: No
Running in Google Colab: No
Token path: /root/.cache/huggingface/token
Has saved token: False
Configured git credential helpers:
FastAI: N/A
Tensorflow: N/A
Torch: 1.14.0a0+44dac51
Jinja2: 3.1.2
Graphviz: N/A
Pydot: N/A
Pillow: 9.2.0
hf_transfer: N/A
gradio: N/A
tensorboard: N/A
numpy: 1.22.2
pydantic: 1.10.4
aiohttp: N/A
ENDPOINT: https://huggingface.co/
HUGGINGFACE_HUB_CACHE: /root/.cache/huggingface/hub
HUGGINGFACE_ASSETS_CACHE: /root/.cache/huggingface/assets
HF_TOKEN_PATH: /root/.cache/huggingface/token
HF_HUB_OFFLINE: False
HF_HUB_DISABLE_TELEMETRY: False
HF_HUB_DISABLE_PROGRESS_BARS: None
HF_HUB_DISABLE_SYMLINKS_WARNING: False
HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
HF_HUB_DISABLE_IMPLICIT_TOKEN: False
HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by adarshxs** [comment]
Hey @Wauplin, the issue was from my side. My network admin had mistakenly blocked huggingface. The issue is now sorted. Thanks!

**Comment by Wauplin** [comment]
Great to hear!
