### ISSUE TITLE
Vague error of 422 Client Error: Unprocessable Entity

### ISSUE THREAD

**Issue by jamesbraza** [huggingface/huggingface_hub#1753]
### Describe the bug

I am getting a vague error when using [`HuggingFaceH4/zephyr-7b-alpha`](https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha) with the `conversational` task: `422 Client Error: Unprocessable Entity`

It would be good to provide a more human-friendly error message, stating that the `conversational` task is unsupported.

### Reproduction

```python
from huggingface_hub import InferenceClient

client = InferenceClient(model="HuggingFaceH4/zephyr-7b-alpha")
output = client.conversational("Hi how are you?")
```

### Logs

```shell
/Users/user/code/repo/venv/bin/python /Users/user/code/play/a.py 
Traceback (most recent call last):
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-alpha

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user/code/play/quick_play_2.py", line 9, in <module>
    hi = client.conversational("Hi how are you?")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/huggingface_hub/inference/_client.py", line 388, in conversational
    response = self.post(json=payload, model=model, task="conversational")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/huggingface_hub/inference/_client.py", line 238, in post
    hf_raise_for_status(response)
  File "/Users/user/code/repo/venv/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 422 Client Error: Unprocessable Entity for url: https://api-inference.huggingface.co/models/HuggingFaceH4/zephyr-7b-alpha (Request ID: <redacted>)
```

### System info

```shell
- huggingface_hub version: 0.17.3
- Platform: macOS-13.5.2-arm64-arm-64bit
- Python version: 3.11.5
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/user/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.1.0
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.1
- pydantic: 2.4.2
- aiohttp: 3.8.6
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /Users/user/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /Users/user/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/user/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment]
Yes, good idea to have better error messages. I opened https://github.com/huggingface/huggingface_hub/pull/1755 to add them. Thanks for suggesting it :)
