### ISSUE TITLE
Improve error message to write to the Hub using DuckDB when repo doesn't exist

### ISSUE THREAD

**Issue by lhoestq** [huggingface/huggingface_hub#1800]
I'm having this error when trying to write data on HF using the `HfFileSystem` and DuckDB, because the new dataset repository doesn't exist.

I think we should improve this error message - at first I thought there was a bug somewhere

```python
>>> from huggingface_hub import HfFileSystem
>>> import duckdb
>>> fs = HfFileSystem()
>>> duckdb.register_filesystem(fs)
>>> duckdb.sql("CREATE TABLE data AS SELECT * FROM 'hf://datasets/lhoestq/demo1@~parquet/**/*.parquet'")
>>> duckdb.sql("COPY data TO 'hf://datasets/lhoestq/tmp-duckdb-export/data.parquet' (FORMAT PARQUET);")
```

```
Exception ignored in: <function AbstractBufferedFile.__del__ at 0x102f99ca0>
Traceback (most recent call last):
  File "/Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/fsspec/spec.py", line 1966, in __del__
    self.close()
  File "/Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/fsspec/spec.py", line 1944, in close
    self.flush(force=True)
  File "/Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/fsspec/spec.py", line 1815, in flush
    if self._upload_chunk(final=force) is not False:
  File "/Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/huggingface_hub/hf_file_system.py", line 425, in _upload_chunk
    path_in_repo=self.resolved_path.path_in_repo,
AttributeError: 'HfFileSystemFile' object has no attribute 'resolved_path'
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[3], line 1
----> 1 duckdb.sql("COPY data TO 'hf://datasets/lhoestq/tmp-duckdb-export/data.parquet' (FORMAT PARQUET);")

Error: Invalid Error: FileNotFoundError: lhoestq/tmp-duckdb-export/data.parquet

At:
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/huggingface_hub/hf_file_system.py(199): resolve_path
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/huggingface_hub/hf_file_system.py(400): __init__
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/huggingface_hub/hf_file_system.py(235): _open
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/fsspec/spec.py(1309): open
  <ipython-input-3-97feb4ec328b>(1): <module>
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3460): run_code
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3400): run_ast_nodes
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3221): run_cell_async
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/core/async_helpers.py(129): _pseudo_sync_runner
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/core/interactiveshell.py(3016): _run_cell
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/core/interactiveshell.py(2961): run_cell
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py(880): interact
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py(887): mainloop
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/terminal/ipapp.py(318): start
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/traitlets/config/application.py(1043): launch_instance
  /Users/quentinlhoest/.pyenv/versions/3.9.15/envs/hf-datasets/lib/python3.9/site-packages/IPython/__init__.py(124): start_ipython
  /Users/quentinlhoest/.pyenv/versions/hf-datasets/bin/ipython(8): <module>
```

**Comment by lhoestq** [comment]
Or maybe auto-create the repository

**Comment by Wauplin** [comment]
Thanks for reporting @lhoestq. I opened a PR with a proposition on how to improve this: https://github.com/huggingface/huggingface_hub/pull/1805.
