### ISSUE TITLE
`TypeError`: huggingface_hub.hf_file_system.HfFileSystem.find() got multiple values for keyword argument 'maxdepth'

### ISSUE THREAD

**Issue by wasertech** [huggingface/huggingface_hub#1872]
### Describe the bug

I noticed this bug a few times now but could not find anything on it and since it's a bit cryptic I will explain for posterity; if you mismatch the following libs....

```
❯ pip show huggingface-hub
Name: huggingface-hub
Version: 0.20.0.dev0
...
❯ pip show datasets
Name: datasets
Version: 2.15.0
...
```

...and try to load a dataset, it will raise the following `TypeError`:
> huggingface_hub.hf_file_system.HfFileSystem.find() got multiple values for keyword argument 'maxdepth'

### Reproduction

```python
ds = load_dataset("wasertech/AGI", split="train") # can be any set
```

### Logs

```shell
Downloading readme: 100%|███████████████████████████████████████████████████████████████████████████████| 23.6k/23.6k [00:00<00:00, 16.3MB/s]
Traceback (most recent call last):
...
File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/assistant/nlp/chains/schema/vectorstore.py", line 82, in get_guidebook_docs
    guidebook = load_dataset("wasertech/AGI", split="train")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/load.py", line 2128, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/load.py", line 1814, in load_dataset_builder
    dataset_module = dataset_module_factory(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/load.py", line 1511, in dataset_module_factory
    raise e1 from None
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/load.py", line 1495, in dataset_module_factory
    ).get_module()
      ^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/load.py", line 1047, in get_module
    data_files = DataFilesDict.from_patterns(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/data_files.py", line 686, in from_patterns
    DataFilesList.from_patterns(
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/data_files.py", line 591, in from_patterns
    resolve_pattern(
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/datasets/data_files.py", line 345, in resolve_pattern
    fs, _, _ = get_fs_token_paths(pattern, storage_options=storage_options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/fsspec/core.py", line 625, in get_fs_token_paths
    paths = [f for f in sorted(fs.glob(paths)) if not fs.isdir(f)]
                               ^^^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/huggingface_hub/hf_file_system.py", line 382, in glob
    return super().glob(path, maxdepth=maxdepth, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/waser/Projets/Assistant/venv/lib/python3.11/site-packages/fsspec/spec.py", line 580, in glob
    allpaths = self.find(root, maxdepth=depth, withdirs=True, detail=True, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: huggingface_hub.hf_file_system.HfFileSystem.find() got multiple values for keyword argument 'maxdepth'
```

### System info

```shell
- huggingface_hub version: 0.20.0.dev0
- Platform: Linux-6.6.1-1-MANJARO-x86_64-with-glibc2.38
- Python version: 3.11.5
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/waser/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: wasertech
- Configured git credential helpers: /usr/lib/git-core/git-credential-libsecret
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 10.0.1
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.24.3
- pydantic: 1.10.13
- aiohttp: 3.8.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/waser/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/waser/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/waser/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by wasertech** [comment]
May this should go in datasets directly... anyways you can easily fix this error by updating  `datasets>=2.15.1.dev0`.

**Comment by wasertech** [comment]
Updating `fsspec>=2023.10.0` did solve the issue.

**Comment by wasertech** [comment]
> [May be it should be pinned somewhere?](https://github.com/huggingface/datasets/issues/6457#issuecomment-1831073813)
