### ISSUE TITLE
PermissionError while using file_download.py with 2 volumes

### ISSUE THREAD

**Issue by vince62s** [huggingface/huggingface_hub#1882]
### Describe the bug

Getting this error:
PermissionError: [Errno 1] Operation not permitted: '../../../../../home/vincent/.cache/huggingface/hub/models--TheBloke--Llama-2-70B-Chat-AWQ/blobs/9c7bfc407ee5611136dd585c545df28abbe146823288f411c6ffdaba4ff1db27' -> '/media/vincent/Extreme SSD/dataAI/TheBloke/model-00002-of-00004.safetensors'

because volume for cache is not the same volume used with "local_dir" setting

### System info

```shell
huggingface-hub           0.19.4
Ubuntu 20.04
```

**Comment by Wauplin** [comment]
Hi @vince62s, I'm sorry you are facing this issue. A few things:
1. Can you [install `huggingface_hub` from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source) and retry? We recently fixed a bug in the "create symlink" step when working on different volumes.
2. Can you paste the entire stacktrace please? With only the error it's hard to know which part failed exactly.
3. Is there a specific need for the local dir and cache dir to be in different volumes? This can be configured with environment variables if needed: https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables

Hope this will help you solve your problem.

**Comment by vince62s** [comment]
this was the backtrace:
```
(pt2.1.0) vincent@vince-ryzen:~/nlp/OpenNMT-py$ python tools/convert_HF_llamalike.py --model_dir "TheBloke/Llama-2-70B-Chat-AWQ" --output "/media/vincent/Extreme SSD/dataAI/TheBloke/Llama-2-70B-Chat-AWQ-onmt.pt" --format safetensors --nshards 4
Backend not specified in config, using Autoawq
starting output shard: 1/4
/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/huggingface_hub/file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in /media/vincent/Extreme SSD/dataAI/TheBloke. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
  warnings.warn(message)
Loading model-00001-of-00004.safetensors
Saving output model shard: 0
starting output shard: 2/4
Loading model-00001-of-00004.safetensors
Loading model-00002-of-00004.safetensors
model-00002-of-00004.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.90G/9.90G [04:39<00:00, 35.4MB/s]
Traceback (most recent call last):
  File "/home/vincent/nlp/OpenNMT-py/tools/convert_HF_llamalike.py", line 324, in <module>
    checkpoint = get_load_ckpt(os.path.split(wmap_path)[0], ckpt)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vincent/nlp/OpenNMT-py/tools/convert_HF_llamalike.py", line 238, in get_load_ckpt
    ckpt_path = huggingface_hub.hf_hub_download(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1485, in hf_hub_download
    _create_symlink(blob_path, local_dir_filepath, new_blob=False)
  File "/home/vincent/miniconda3/envs/pt2.1.0/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 932, in _create_symlink
    os.symlink(src_rel_or_abs, abs_dst)
PermissionError: [Errno 1] Operation not permitted: '../../../../../home/vincent/.cache/huggingface/hub/models--TheBloke--Llama-2-70B-Chat-AWQ/blobs/9c7bfc407ee5611136dd585c545df28abbe146823288f411c6ffdaba4ff1db27' -> '/media/vincent/Extreme SSD/dataAI/TheBloke/model-00002-of-00004.safetensors'

```

FYI the script is also there:
https://github.com/OpenNMT/OpenNMT-py/blob/master/tools/convert_HF_llamalike.py#L233-L255

The reason I am using the hub download is because I can download one shard at a time hence not require a big amount of RAM as it is the case with AutoModel etc ...

I haven't tried from master yet, will do so.

**Comment by Wauplin** [comment]
Hey @vince62s , thanks for sharing more details. This is indeed a corner case we've not handled. I opened a PR that should solve it. The file will be copied without symlinks (i.e. not efficient in term of hard drive usage) but that's the only solution when symlinks doesn't work.
