### ISSUE TITLE
problem with spaces when working with a custom model file

### ISSUE THREAD

**Issue by not-lain** [huggingface/huggingface_hub#1883]
### Describe the bug

when I created this [hf space](https://huggingface.co/spaces/not-lain/running_stable_diffusion_from_a_ckpt_file) i faced the a problem which is when using `StableDiffusionPipeline.from_single_file` we need to provide the file url and it seems that in spaces there is a problem since they automatically parse the url and add a tag to the the original model mentioning that my space is using their model.
Now problem is my url is in the following format `hf.co/user/model/file.ckpt` instead of `hf.co/user/model`  (┬┬﹏┬┬)

### Reproduction

* requirements
```
torch 
diffusers 
gradio 
omegaconf
transformers
```
* app.py 
```py
from diffusers import StableDiffusionPipeline
import gradio as gr
pipeline = StableDiffusionPipeline.from_single_file(
    "https://huggingface.co/waifu-research-department/Rem/blob/main/rem_3k.ckpt",
).to("cuda")


def text2img(positive_prompt,negative_prompt):
    image = pipeline(postive_prompt,negative_prompt=negative_prompt).images[0]
    return image

gr.Interface(text2img,["text","text"],["image"],examples=[["rem","3D"]],description=description).launch()
```

### Logs

```shell
st_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /waifu-research-department/Rem/resolve/main/rem_3k.ckpt (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f52c40f03a0>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: 7e0451ed-b2dd-4d39-a90b-49eccb4399bd)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/app/app.py", line 5, in <module>
    pipeline = StableDiffusionPipeline.from_single_file(
  File "/home/user/.local/lib/python3.10/site-packages/diffusers/loaders/single_file.py", line 249, in from_single_file
    pretrained_model_link_or_path = hf_hub_download(
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1377, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
````
```


### System info

```shell
why is this a required field man, it's huggingface spaces envirenment here, i donno (┬┬﹏┬┬)
```

**Comment by not-lain** [comment]
additional info : I tried going through [spaces-config](https://huggingface.co/docs/hub/spaces-config-reference) and adding `models` parameter to my config hoping that this will be a workraround but it seems that my method failed

fixes tier list: 
1. add a parameter to spaces config that would disable the tagging process (which reminds me that even when my space is private i keep tagging the original model, meaning that when i go the model page i still find my space there tagged, even though they can't access it) 
2. parse the url 
3.  try except
4.  add an exception to `StableDiffusionPipeline.from_single_file`

**Comment by Wauplin** [comment]
What is the bug exactly? Is it that you can't load the model? If that's the case, `diffusers` repository would be more appropriate to ask for help.

Or is it that you want to connect the model and the Space on the Hub? I think it's already done: 
![image](https://github.com/huggingface/huggingface_hub/assets/11801849/11fd0ff5-42da-44b4-9d39-575ad2e0c5d7)

**Comment by Wauplin** [comment]
```py
  File "/home/user/app/app.py", line 60, in text2img
    if log == "no GPU available":
UnboundLocalError: local variable 'log' referenced before assignment
```

looks like the error now is not related to this initial issue you've described.

And that the model has been downloaded correctly:

```
rem_3k.ckpt:  77%|███████▋  | 1.64G/2.13G [00:06<00:01, 298MB/s]
rem_3k.ckpt: 100%|█████████▉| 2.13G/2.13G [00:06<00:00, 317MB/s]
```

Can we close this issue then?
