### ISSUE TITLE
Consistency check failed: file should be of size 440449768 but has size 4122356 (model.safetensors).

### ISSUE THREAD

**Issue by Pastrick13** [huggingface/huggingface_hub#1946]
OSError                                   Traceback (most recent call last)
Cell In[10], [line 14](vscode-notebook-cell:?execution_count=10&line=14)
    # Load pre-trained BERT model and tokenizer
     tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
---> bert_model = TFBertModel.from_pretrained('bert-base-uncased', force_download=True, resume_download=False)
  # Example: Apply BERT embeddings to a column in your data
     text_column = 'Text_Column'  # Adjust this based on your actual column name

OSError: Consistency check failed: file should be of size 440449768 but has size 4122356 (model.safetensors).

**Comment by Wauplin** [comment]
@Pastrick13 sorry you're facing this issue. Did you try to re-run the command and got the same error? This error is raised when the downloaded content does not match the expected size. It can happen on slow/intermittent network and is most of the time a transient error. Unfortunately we can't do much about it except retrying as it's very hard to investigate (I actually never reproduced this issue myself on a laptop).

**Comment by Wauplin** [comment]
Closing this issue as stale. Feel free to comment and I'll reopen :)

**Comment by Unlicensed-driver-ljx** [comment]
pytorch_model-00001-of-00003.bin:   0%|▏                                                                                                                             | 14.6M/9.95G [00:03<6:45:59, 408kB/s]
Fetching 12 files:  42%|█████████████████████████████████████████████████████████████▋                                                                                      | 5/12 [00:05<00:08,  1.18s/it]
pytorch_model-00002-of-00003.bin:   0%|▏                                                                                                                             | 15.2M/9.90G [00:01<3:59:38, 688kB/s]
pytorch_model-00003-of-00003.bin:   0%|▎                                                                                                                             | 18.3M/6.24G [00:04<5:08:35, 336kB/s]
Traceback (most recent call last):  0%|▏                                                                                                                             | 15.2M/9.90G [00:01<3:59:14, 689kB/s]
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,                                                                                                                       | 18.3M/6.24G [00:04<5:08:02, 337kB/s]
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/local_llm/local_llm/__main__.py", line 22, in <module>
    model = LocalLM.from_pretrained(
  File "/opt/local_llm/local_llm/local_llm.py", line 50, in from_pretrained
    model_path = download_model(model, **kwargs)
  File "/opt/local_llm/local_llm/utils/model.py", line 44, in download_model
    repo_path = snapshot_download(repo_id=model, repo_type=type, cache_dir=cache_dir, resume_download=True,
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "/usr/local/lib/python3.8/dist-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/_snapshot_download.py", line 283, in _inner_hf_hub_download
    return hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
    http_get(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 552, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 9948728430 but has size 14559267 (pytorch_model-00001-of-00003.bin).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
