### ISSUE TITLE
TypeError: TextGenerationStreamResponse.__init__() got an unexpected keyword argument 'index'

### ISSUE THREAD

**Issue by grumpyp** [huggingface/huggingface_hub#2046]
### Describe the bug

I've experienced several issues with the `huggingface_hub` package but this one is for sure a bug.

the reproduction script 
leads to this one:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrickgerard/Documents/GitHub/huggingface/venv/lib/python3.11/site-packages/huggingface_hub/inference/_common.py", line 272, in _stream_text_generation_response
    output = TextGenerationStreamResponse(**json_payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TextGenerationStreamResponse.__init__() got an unexpected keyword argument 'index'
```

I tried it on my Mac and then switched to a VPS with.

```

Python: Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux


root@ubuntu-s-1vcpu-512mb-10gb-fra1-01:/home/test#  cat /etc/*release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
```

on my M1 mac I use `Python 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin`

the package is on version `huggingface-hub==0.20.3`

### Reproduction

```
from huggingface_hub import InferenceClient

client = InferenceClient("https://pjhv1e6qntb81fhl.us-east-1.aws.endpoints.huggingface.cloud/")
for token in client.text_generation("How do you make cheese?", max_new_tokens=12, stream=True):
    print(token)
```

### System info

```shell
Copy-and-paste the text below in your GitHub issue.

- huggingface_hub version: 0.20.3
- Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /root/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.0.3
- Graphviz: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: N/A
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /root/.cache/huggingface/hub
- HF_ASSETS_CACHE: /root/.cache/huggingface/assets
- HF_TOKEN_PATH: /root/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by grumpyp** [comment]
Examples came from:

https://huggingface.co/docs/text-generation-inference/basic_tutorials/consuming_tgi

**Comment by Wauplin** [comment]
Hi @grumpyp thanks for reporting and sorry for the inconvenience. The issue has been fixed in https://github.com/huggingface/huggingface_hub/issues/2005 and will be shipped in the next release that will happen soon (this week). In the meantime you can already benefit from the fix by installing the library[ from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source).
