### ISSUE TITLE
huggingface_hub.utils._errors.HfHubHTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/timm/vit_large_patch16_384.augreg_in21k_ft_in1k/resolve/main/model.safetensors

### ISSUE THREAD

**Issue by MirandaLv** [huggingface/huggingface_hub#2060]
### Describe the bug

Got below error huggingface_hub.utils._errors.HfHubHTTPError: 503 Server Error:

Is it comes from the maintenance? Thanks. 

Traceback (most recent call last):
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/timm/vit_large_patch16_384.augreg_in21k_ft_in1k/resolve/main/model.safetensors

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train.py", line 77, in <module>
    transformer_encoders = timm.create_model("vit_large_patch16_384", pretrained=True)
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/timm/models/_factory.py", line 118, in create_model
    **kwargs,
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/timm/models/vision_transformer.py", line 1607, in vit_large_patch16_384
    model = _create_vision_transformer('vit_large_patch16_384', pretrained=pretrained, **dict(model_args, **kwargs))
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/timm/models/vision_transformer.py", line 1455, in _create_vision_transformer
    **kwargs,
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/timm/models/_builder.py", line 399, in build_model_with_cfg
    strict=pretrained_strict,
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/timm/models/_builder.py", line 186, in load_pretrained
    state_dict = load_state_dict_from_hf(pretrained_loc)
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/timm/models/_hub.py", line 179, in load_state_dict_from_hf
    cached_safe_file = hf_hub_download(repo_id=hf_model_id, filename=safe_filename, revision=hf_revision)
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 1199, in hf_hub_download
    timeout=etag_timeout,
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/huggingface_hub/file_download.py", line 1541, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/opt/conda/envs/depth_grid/lib/python3.7/site-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/timm/vit_large_patch16_384.augreg_in21k_ft_in1k/resolve/main/model.safetensors

### Reproduction

import timm

transformer_encoders = timm.create_model("vit_large_patch16_384", pretrained=True)

### System info

```shell
huggingface-hub           0.16.4
python 3.7.7
```

**Comment by Wauplin** [comment]
Small nit: if you update your environment to python3.8+ and huggingface_hub>=0.20, the library would default back to the locally saved files in case of outage. This means that if you've already instantiated the model once, you would still be able to reload it. Another solution is to set `HF_HUB_OFFLINE=1` as environment variable.

**Comment by MirandaLv** [comment]
Oh great, thank you for the update and sorry that I just saw this message. Yes, my code was running the next day :)
