### ISSUE TITLE
`huggingface-cli` fails to upload when `HF_ENDPOINT` is set

### ISSUE THREAD

**Issue by padeoe** [huggingface/huggingface_hub#2114]
### Describe the bug

This bug is triggered under the following conditions:

- If `HF_ENDPOINT` is set and the hostname is not in the form of `(hub-ci.)?huggingface.co`.
- Use `huggingface-cli upload` command.

This issue seems to be related to [another issue](https://github.com/huggingface/datasets/issues/6728) I found.

### Reproduction

1. Create a repo on huggingface.co: `username/reponame`
2. Set a custom `HF_ENDPOINT`.
```bash
export HF_ENDPOINT=https://hf-mirror.com
```
3. upload a directory to remote repo with `huggingface-cli`.
```bash
huggingface-cli upload --token hf_*** username/reponame . .
```
Output:
```
Consider using hf_transfer for faster uploads. This solution comes with some limitations. See https://huggingface.co/docs/huggingface_hub/hf_transfer for more details.
Traceback (most recent call last):
  File "/home/padeoe/.local/bin/huggingface-cli", line 8, in 
    sys.exit(main())
  File "/home/padeoe/.local/lib/python3.10/site-packages/huggingface_hub/commands/huggingface_cli.py", line 49, in main
    service.run()
  File "/home/padeoe/.local/lib/python3.10/site-packages/huggingface_hub/commands/upload.py", line 190, in run
    print(self._upload())
  File "/home/padeoe/.local/lib/python3.10/site-packages/huggingface_hub/commands/upload.py", line 251, in _upload
    repo_id = self.api.create_repo(
  File "/home/padeoe/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/padeoe/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3370, in create_repo
    return RepoUrl(d["url"], endpoint=self.endpoint)
  File "/home/padeoe/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 437, in __init__
    repo_type, namespace, repo_name = repo_type_and_id_from_hf_id(self, hub_url=self.endpoint)
  File "/home/padeoe/.local/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 227, in repo_type_and_id_from_hf_id
    raise ValueError(f"Unable to retrieve user and repo ID from the passed HF ID: {hf_id}")
ValueError: Unable to retrieve user and repo ID from the passed HF ID: https://huggingface.co/username/reponame
```

Errors are observed, indicating that the connection is still to `https://huggingface.co` instead of the `https://hf-mirror.com` set by `HF_ENDPOINT`.

It's worth noting that if `HF_ENDPOINT` is set to `https://huggingface.co`, the above issue does not occur.

Strangely, this issue does not occur when using Python code:

```Python
import os
os.environ['HF_ENDPOINT']='https://hf-mirror.com'

import huggingface_hub
huggingface_hub.login("hf_***")

from huggingface_hub import HfApi
api=HfApi()
api.upload_folder(
    repo_id="username/reponame",
    folder_path="/path/to/your/repo",
    path_in_repo="."
)
```

### System info

```shell
- huggingface_hub version: 0.21.4
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/padeoe/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: N/A
- Graphviz: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.1
- pydantic: 1.10.7
- aiohttp: 3.9.3
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/padeoe/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/padeoe/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/padeoe/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Fixed by https://github.com/huggingface/huggingface_hub/pull/2120 :)
