### ISSUE TITLE
gpt2 download keeps failing at consistency checking for 64-8bits.tflite

### ISSUE THREAD

**Issue by JamesHuang2004** [huggingface/huggingface_hub#2210]
### Describe the bug

Running " huggingface-cli download gpt2" failed in the end: 

OSError: Consistency check failed: file should be of size 125162496 but has size 90309182 (64-8bits.tflite).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub. 

Running  "huggingface-cli download gpt2 force_download=True resume_download=False" does nothing
 

### Reproduction

huggingface-cli download gpt2

... failed as described...

huggingface-cli download gpt2 force_download=True resume_download=False

... Nothing is fetched.

### Logs

```shell
(base) billhuang@bh-m1-max llm.c % huggingface-cli download gpt2                    
Consider using `hf_transfer` for faster downloads. This solution comes with some limitations. See https://huggingface.co/docs/huggingface_hub/hf_transfer for more details.
Fetching 26 files:   0%|                                                                                         | 0/26 [00:00<?, ?it/s]downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/64.tflite to /Users/billhuang/.cache/huggingface/hub/tmpq8uvbwc6
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/model.safetensors to /Users/billhuang/.cache/huggingface/hub/tmp8rlbidop
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/64-fp16.tflite to /Users/billhuang/.cache/huggingface/hub/tmppp897p4w
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/64-8bits.tflite to /Users/billhuang/.cache/huggingface/hub/tmpgo7y8wan
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/flax_model.msgpack to /Users/billhuang/.cache/huggingface/hub/tmpusq8vd4d
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/onnx/decoder_model_merged.onnx to /Users/billhuang/.cache/huggingface/hub/tmp1uh_1ghd
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/onnx/decoder_with_past_model.onnx to /Users/billhuang/.cache/huggingface/hub/tmpnteqrjzy
                                                                                                                                       downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/onnx/decoder_model.onnx to /Users/billhuang/.cache/huggingface/hub/tmptuqniqbw                                                                               | 0.00/125M [00:00<?, ?B/s]
64-fp16.tflite:  24%|██████████████████▉                                                            | 59.4M/248M [00:47<02:29, 1.26MB/s]
64.tflite:  12%|██████████▏                                                                         | 59.9M/496M [00:47<05:44, 1.26MB/s]
onnx/decoder_model.onnx:   9%|██████▏                                                               | 58.3M/654M [00:46<07:50, 1.26MB/s]
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/onnx/tokenizer.json to /Users/billhuang/.cache/huggingface/hub/tmps4guhc88████████████▉                                                            | 59.4M/248M [00:47<02:31, 1.25MB/s]
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/onnx/special_tokens_map.json to /Users/billhuang/.cache/huggingface/hub/tmpdksrc53h|█████                                                          | 52.4M/655M [00:40<07:45, 1.29MB/s]
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/onnx/tokenizer_config.json to /Users/billhuang/.cache/huggingface/hub/tmpfekpe6hy██▏                                                               | 58.3M/654M [00:46<07:55, 1.25MB/s]
onnx/special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████| 99.0/99.0 [00:00<00:00, 366kB/s]
onnx/tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████| 234/234 [00:00<00:00, 1.20MB/s]
                                                                                                                                       downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/onnx/vocab.json to /Users/billhuang/.cache/huggingface/hub/tmpyucpa_t8p.json:   0%|                                                                          | 0.00/99.0 [00:00<?, ?B/s]
onnx/tokenizer_config.json:   0%|                                                                             | 0.00/234 [00:00<?, ?B/sdownloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/rust_model.ot to /Users/billhuang/.cache/huggingface/hub/tmps75_dqx8
onnx/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████| 2.11M/2.11M [00:01<00:00, 1.66MB/s]
onnx/vocab.json: 100%|███████████████████████████████████████████████████████████████████████████████| 798k/798k [00:00<00:00, 1.30MB/s]
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/tf_model.h5 to /Users/billhuang/.cache/huggingface/hub/tmpbtl1it94: 100%|█████████████████████████████████████████████████████████████████████████| 2.11M/2.11M [00:01<00:00, 1.66MB/s]
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/tokenizer.json to /Users/billhuang/.cache/huggingface/hub/tmpshy0mzrh███████████████████████████████████████████████████████████████████████████████| 798k/798k [00:00<00:00, 1.30MB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 1.62MB/s]
onnx/decoder_with_past_model.onnx:  10%|█████▊                                                      | 62.9M/654M [00:48<07:25, 1.33MB/sdownloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/tokenizer_config.json to /Users/billhuang/.cache/huggingface/hub/tmp8d8eaixn███████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:00<00:00, 1.62MB/s]
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████| 26.0/26.0 [00:00<00:00, 133kB/s]
downloading https://huggingface.co/gpt2/resolve/607a30d783dfa663caf39e06633721c8d4cfcd7e/vocab.json to /Users/billhuang/.cache/huggingface/hub/tmpp42wgynh
vocab.json: 100%|██████████████████████████████████████████████████████████████████████████████████| 1.04M/1.04M [00:00<00:00, 1.16MB/s]
64-8bits.tflite:  72%|████████████████████████████████████████████████████████▎                     | 90.3M/125M [01:07<00:26, 1.34MB/s]
model.safetensors:  17%|████████████▌                                                               | 90.6M/548M [01:07<05:38, 1.35MB/s]
Fetching 26 files:   4%|███                                                                              | 1/26 [01:09<29:02, 69.71s/it]
rust_model.ot:  16%|████████████▊                                                                    | 111M/703M [00:58<05:12, 1.89MB/s]
tf_model.h5:  58%|████████████████████████████████████████████████▎                                  | 290M/498M [02:09<01:32, 2.24MB/s]
flax_model.msgpack:  72%|██████████████████████████████████████████████████████▎                     | 356M/498M [02:59<01:11, 1.98MB/s]
onnx/decoder_with_past_model.onnx:  54%|█████████████████████████████████                            | 355M/654M [02:59<02:30, 1.98MB/s]
onnx/decoder_model_merged.onnx:  54%|██████████████████████████████████▋                             | 355M/655M [02:59<02:31, 1.98MB/s]
Traceback (most recent call last):████████████████████████████████▎                                  | 290M/498M [02:09<01:24, 2.48MB/s]
  File "/Users/billhuang/miniforge3/bin/huggingface-cli", line 8, in <module>                        | 178M/655M [01:49<03:58, 2.00MB/s]
    sys.exit(main())erged.onnx:  54%|██████████████████████████████████▋                             | 355M/655M [02:59<02:02, 2.46MB/s]
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/commands/huggingface_cli.py", line 49, in main 2.43MB/s]
    service.run()
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/commands/download.py", line 161, in run
    print(self._download())  # Print path to downloaded files
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/commands/download.py", line 202, in _download
    return snapshot_download(
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 316, in snapshot_download
    thread_map(
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 94, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/tqdm/contrib/concurrent.py", line 76, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, **map_args), **kwargs))
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/Users/billhuang/miniforge3/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/Users/billhuang/miniforge3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/billhuang/miniforge3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/billhuang/miniforge3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/_snapshot_download.py", line 290, in _inner_hf_hub_download
    return hf_hub_download(
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/utils/_validators.py", line 119, in _inner_fn
    return fn(*args, **kwargs)
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1492, in hf_hub_download
    http_get(
  File "/Users/billhuang/miniforge3/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 566, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 125162496 but has size 90309182 (64-8bits.tflite).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.


(base) billhuang@bh-m1-max llm.c % huggingface-cli download gpt2 force_download=True resume_download=False
Consider using `hf_transfer` for faster downloads. This solution comes with some limitations. See https://huggingface.co/docs/huggingface_hub/hf_transfer for more details.
Fetching 0 files: 0it [00:00, ?it/s]
/Users/billhuang/.cache/huggingface/hub/models--gpt2/snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e
```

### System info

```shell
- huggingface_hub version: 0.22.2
- Platform: macOS-14.4.1-arm64-arm-64bit
- Python version: 3.9.15
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /Users/billhuang/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: osxkeychain
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.13.1
- Jinja2: 3.1.2
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 9.2.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.23.5
- pydantic: N/A
- aiohttp: 3.8.3
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /Users/billhuang/.cache/huggingface/hub
- HF_ASSETS_CACHE: /Users/billhuang/.cache/huggingface/assets
- HF_TOKEN_PATH: /Users/billhuang/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by JamesHuang2004** [comment]
Thanks Wauplin. I tried your suggestion:

huggingface-cli download gpt2 64-8bits.tflite --force-download
Consider using `hf_transfer` for faster downloads. This solution comes with some limitations. See https://huggingface.co/docs/huggingface_hub/hf_transfer for more details.
downloading https://huggingface.co/gpt2/resolve/main/64-8bits.tflite to /Users/billhuang/.cache/huggingface/hub/tmp97_vwzl_
64-8bits.tflite: 100%|███████████████████████████████████████████████████████████████████████████████| 125M/125M [00:15<00:00, 8.04MB/s]
/Users/billhuang/.cache/huggingface/hub/models--gpt2/snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e/64-8bits.tflite

But after this, when I continue to run: 

huggingface-cli download gpt2 

the same error shows up:
OSError: Consistency check failed: file should be of size 248269688 but has size 242295231 (64-fp16.tflite).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.

Then trying this: 
 huggingface-cli download gpt2 force_download=True resume_download=False

getting this: 

Consider using `hf_transfer` for faster downloads. This solution comes with some limitations. See https://huggingface.co/docs/huggingface_hub/hf_transfer for more details.
Fetching 0 files: 0it [00:00, ?it/s]
/Users/billhuang/.cache/huggingface/hub/models--gpt2/snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e

**Comment by Wauplin** [comment]
If `huggingface-cli download gpt2 64-8bits.tflite --force-download` worked, it definitely looks like there are corrupted files in there. Running `huggingface-cli download gpt2 --force-download` should help to fix it.

**Comment by JamesHuang2004** [comment]
Thanks Wauplin.

huggingface-cli download gpt2 --force-download 

this keeps failing at different files. I am trying to download nanoGPT of GPT-2, the GPT-2 (124M) model, what tag should I specify?

**Comment by JamesHuang2004** [comment]
Thanks man - I figured it out. Have a good day!

**Comment by JamesHuang2004** [comment]
Thanks a ton!

**Comment by Wauplin** [comment]
Glad you figure it out and sorry again for the inconvenience. Have fun!

**Comment by Ga-Lee** [comment]
> Thanks man - I figured it out. Have a good day!

Hi, glad to find you !  Could you please tell me what is the cause for the issue? I met this issue as well and do not know how to fix it. Thanks for your response!
