### ISSUE TITLE
Issue occured when using jupyter lab

### ISSUE THREAD

**Issue by elysiaforme** [huggingface/huggingface_hub#2246]
When using geemap,after runing :
Map = geemap.Map()
Map
there is a mitake about the interact widow of the map,which says:
Failed to load model class 'VBoxModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
    at f.loadClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:75057)
    at f.loadModelClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:10729)
    at f._make_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:7517)
    at f.new_model (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:5137)
    at f.handle_comm_open (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/336.ebc7a55ea1768712771f.js?v=ebc7a55ea1768712771f:1:3894)
    at _handleCommOpen (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.a63a8d293fb35a52dc25.js?v=a63a8d293fb35a52dc25:1:73473)
    at C._handleCommOpen (http://localhost:8888/static/lab/jlab_core.1058fa9b4dc10b69b0bb.js:2:854081)
    at async C._handleMessage (http://localhost:8888/static/lab/jlab_core.1058fa9b4dc10b69b0bb.js:2:856382)
![1](https://github.com/huggingface/huggingface_hub/assets/167158560/3f76a37a-267a-428d-a567-e3b1a7a9fbcd)

**Comment by Wauplin** [comment]
Hi @elysiaforme, this error doesn't seem related to the `huggingface_hub` library in any way. Could you provide more context about it? Otherwise I'll close this issue. Thanks in advance!

**Comment by elysiaforme** [comment]
Oops,sorry about that!I just made a  mistake,I'll close this right away.

**Comment by Wauplin** [comment]
No worries, hope you'll solve your issue quickly :)
