### ISSUE TITLE
huggingface_hub dowload failed

### ISSUE THREAD

**Issue by Wenhai-Zhang** [huggingface/huggingface_hub#2362]
### Describe the bug

I checked the source of error "Distant resource does not have a Content-Length." The error seems to be caused by the size being None in the obtained HfFilemetadata information. Or rather, due to network connection, I have tried many times.
```
HfFileMetadata(commit_hash='c206aab77ae5967a069c4200ecb1858588528c9d', etag='018cdf165c9a3263645d925598e45f8f952990d4', location='https://hf-mirror.com/togethercomputer/evo-1-131k-base/resolve/c206aab77ae5967a069c4200ecb1858588528c9d/README.md', size=5166)
HfFileMetadata(commit_hash='c206aab77ae5967a069c4200ecb1858588528c9d', etag='d79c491957cf52bcae1722635ccdaade2fa79a2a', location='https://hf-mirror.com/togethercomputer/evo-1-131k-base/resolve/c206aab77ae5967a069c4200ecb1858588528c9d/engine.py', size=None)

```

### Reproduction

```
from huggingface_hub import snapshot_download
snapshot_download(repo_id="togethercomputer/evo-1-131k-base", revision="1.1_fix")
```

### Logs

```shell
Traceback (most recent call last):
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1754, in _get_metadata_or_catch_error
    raise FileMetadataError("Distant resource does not have a Content-Length.")
huggingface_hub.utils._errors.FileMetadataError: Distant resource does not have a Content-Length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/work/wenhai/glm4tax/script/model_download.py", line 2, in <module>
    snapshot_download(repo_id="togethercomputer/evo-1-131k-base", revision="1.1_fix")
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 294, in snapshot_download
    thread_map(
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/wenhai/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/wenhai/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 268, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/wenhai/miniconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1826, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```

### System info

```shell
- huggingface_hub version: 0.23.4
- Platform: Linux-4.18.0-477.10.1.el8_8.x86_64-x86_64-with-glibc2.28
- Python version: 3.11.9
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/wenhai/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.0
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.3.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://hf-mirror.com
- HF_HUB_CACHE: /home/wenhai/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/wenhai/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/wenhai/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by padeoe** [comment]
Hi @Wenhai-Zhang 
The problem you encountered is actually due to a bug on the hf-mirror site, not on huggingface.co. As the site maintainer of hf-mirror, I apologize for any inconvenience caused. This bug was fixed 3 days ago. For more details, you can refer to [this issue](https://github.com/padeoe/hf-mirror-site/issues/31).

Could you please check if the problem still persists for you?

**Comment by Wenhai-Zhang** [comment]
Thanks. I have successfully downloaded the data. I have no problem.

**Comment by VINNY-LUO** [comment]
> 嗨，张@Wenhai您遇到的问题实际上是由于 hf-mirror 站点上的错误造成的，而不是 huggingface.co 上的错误。作为hf-mirror的网站维护者，对于给您带来的任何不便，我深表歉意。此错误已于 3 天前修复。更多细节可以参考[本期](https://github.com/padeoe/hf-mirror-site/issues/31)。
> 
> 您能检查一下问题是否仍然存在吗？

Hi,padeoe!I have made the same mistake as him**"huggingface_hub.errors.FileMetadataError: Distant resource does not have a Content-Length"**.

In the lib/python3.x/site-packages/huggingface_hub/constants.py folder of the conda environment,
I replace both HUGGINGFACE_CO_URL_HOME and _HF_DEFAULT_ENDPOINT with: "https://hf-mirror.com".Could you please take a look at how to fix it?
@padeoe 
**log**
```(rlhflow) mqluo@ubuntu:~/fall2025/Samplers-in-Online-DPO/alignment$ hf download PKU-Alignment/alpaca-7b-reproduced 
Fetching 15 files:   0%|                                                                                                                    | 0/15 [00:00<?, ?it/s]Downloading 'model-00003-of-00007.safetensors' to '/home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/b118a476c11bfbab90e0414134121c730cc7235229b72d3adabb1d96e8259a00.incomplete'
Downloading 'model-00001-of-00007.safetensors' to '/home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/c7513e52a42b62a99de58e891d9539577a4204d7f38a27f18fd4353e056b00b4.incomplete'
Downloading 'model-00006-of-00007.safetensors' to '/home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/b2ba904cb300acc4df6c8001cf164ab7adfcff69280b987f61188f6c85587d2a.incomplete'
Downloading 'model-00005-of-00007.safetensors' to '/home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/1014ff3d1b8a7e8a6bb1320989c2f074f6e8b25546b3e9b83620b583f0591d31.incomplete'
Downloading 'model-00002-of-00007.safetensors' to '/home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/b919c2b9ebd40e1392410895ababd4507333fadfba332b36116125c110a52248.incomplete'
Downloading 'model-00004-of-00007.safetensors' to '/home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/50b70595e464fc08053a35f33b976285bd21290a32d6b797248a7f65de58fce7.incomplete'
Fetching 15 files:   0%|                                                                                                                    | 0/15 [00:01<?, ?it/s]
model-00005-of-00007.safetensors:   0%|                                                                                                | 0.00/1.93G [00:00<?, ?B/sDownloading 'model-00007-of-00007.safetensors' to '/home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/bbcdab0eb092888e4e2fd6e7eb8197d55d875dcd422630156fbdb51c3cdcc64a.incomplete'                                                                                       | 0.00/1.99G [00:00<?, ?B/s]
model-00001-of-00007.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.98G/1.98G [13:09<00:00, 2.51MB/s]
Download complete. Moving file to /home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/c7513e52a42b62a99de58e891d9539577a4204d7f38a27f18fd4353e056b00b4.safetensors:  18%|████████████████                                                                       | 367M/1.99G [13:06<1:23:43, 323kB/s]
model-00002-of-00007.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.99G/1.99G [13:43<00:00, 2.42MB/s]
Download complete. Moving file to /home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/b919c2b9ebd40e1392410895ababd4507333fadfba332b36116125c110a52248.safetensors:  19%|████████████████▌                                                                      | 377M/1.99G [13:35<1:20:08, 335kB/s]
model-00006-of-00007.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.93G/1.93G [16:25<00:00, 1.96MB/s]
Download complete. Moving file to /home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/b2ba904cb300acc4df6c8001cf164ab7adfcff69280b987f61188f6c85587d2a.safetensors:  23%|████████████████████▋                                                                    | 461M/1.99G [16:11<53:45, 474kB/s]
model-00004-of-00007.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.99G/1.99G [17:46<00:00, 1.87MB/s]
Download complete. Moving file to /home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/50b70595e464fc08053a35f33b976285bd21290a32d6b797248a7f65de58fce7.safetensors:  35%|██████████████████████████████▌                                                         | 692M/1.99G [17:44<09:24, 2.30MB/s]
model-00005-of-00007.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.93G/1.93G [21:39<00:00, 1.49MB/s]
Download complete. Moving file to /home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/1014ff3d1b8a7e8a6bb1320989c2f074f6e8b25546b3e9b83620b583f0591d31.safetensors:  76%|██████████████████████████████████████████████████████████████████▍                    | 1.52G/1.99G [21:39<02:13, 3.53MB/s]
model-00003-of-00007.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.99G/1.99G [23:14<00:00, 1.43MB/s]
Download complete. Moving file to /home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/b118a476c11bfbab90e0414134121c730cc7235229b72d3adabb1d96e8259a00.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.99G/1.99G [23:14<00:00, 5.11MB/s]
model-00007-of-00007.safetensors: 100%|███████████████████████████████████████████████████████████████████████████████████████| 1.66G/1.66G [23:19<00:00, 1.18MB/s]
Download complete. Moving file to /home/mqluo/.cache/huggingface/hub/models--PKU-Alignment--alpaca-7b-reproduced/blobs/bbcdab0eb092888e4e2fd6e7eb8197d55d875dcd422630156fbdb51c3cdcc64a
Traceback (most recent call last): 96%|███████████████████████████████████████████████████████████████████████████████████▏   | 1.58G/1.66G [23:11<00:16, 4.35MB/s]
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1585, in _get_metadata_or_catch_error
    raise FileMetadataError("Distant resource does not have a Content-Length.")
huggingface_hub.errors.FileMetadataError: Distant resource does not have a Content-Length.███████████████████████████████████▉| 1.66G/1.66G [23:19<00:00, 8.69MB/s]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mqluo/miniforge3/envs/rlhflow/bin/hf", line 7, in <module>
    sys.exit(main())
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/cli/hf.py", line 59, in main
    service.run()
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/cli/download.py", line 136, in run
    print(self._download())  # Print path to downloaded files
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/cli/download.py", line 169, in _download
    return snapshot_download(
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 332, in snapshot_download
    thread_map(
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 306, in _inner_hf_hub_download
    return hf_hub_download(
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1010, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1117, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/home/mqluo/miniforge3/envs/rlhflow/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1661, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.```

**Comment by padeoe** [comment]
@VINNY-LUO The issue encountered today was with hf-mirror.com. It has been fixed.

**Comment by JHex-git** [comment]
Hi @padeoe , I also meet this issue when I download model(meta-llama/llama-3.1-8B) using `https://hf-mirror.com` as `HF_ENDPOINT`. Could you please take some time to check the fix? Here is the log, thank you!
```
Fetching 17 files:   0%|                                                                                                                                                                   | 0/17 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1585, in _get_metadata_or_catch_error
    raise FileMetadataError("Distant resource does not have a Content-Length.")
huggingface_hub.errors.FileMetadataError: Distant resource does not have a Content-Length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/hf", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/cli/hf.py", line 59, in main
    service.run()
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/cli/download.py", line 136, in run
    print(self._download())  # Print path to downloaded files
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/cli/download.py", line 169, in _download
    return snapshot_download(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/_snapshot_download.py", line 332, in snapshot_download
    thread_map(
  File "/usr/local/lib/python3.12/dist-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/_snapshot_download.py", line 306, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1010, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1117, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py", line 1661, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
```

**Comment by padeoe** [comment]
@JHex-git Thanks for the report. I've fixed this issue; could you please test it again?

**Comment by JHex-git** [comment]
Fixed! Thank you for your quick response! @padeoe
