### ISSUE TITLE
`huggingface-cli` fails to download model because of missing `.incomplete` file

### ISSUE THREAD

**Issue by mlinke-ai** [huggingface/huggingface_hub#2374]
### Describe the bug

The `huggingface-cli` fails to download the `microsoft/phi-3-mini-4k-instruct-onnx` model because the `.incomplete` file of the `.onnx` data file is missing.

I assume the file should be created during download to track progress and later resume aborted downloads.

### Reproduction

Run the following command:

```text
huggingface-cli download microsoft/Phi-3-mini-4k-instruct-onnx --include "cpu_and_mobile/cpu-int4-rtn-block-32/*" --local-dir models/phi-3-mini-4k-instruct-onnx
```

### Logs

```shell
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\Scripts\huggingface-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\commands\huggingface_cli.py", line 51, in main
    service.run()
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\commands\download.py", line 146, in run
    print(self._download())  # Print path to downloaded files
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\commands\download.py", line 180, in _download
    return snapshot_download(
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 294, in snapshot_download
    thread_map(
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\tqdm\contrib\concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Program Files\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\_snapshot_download.py", line 268, in _inner_hf_hub_download
    return hf_hub_download(
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 1202, in hf_hub_download
    return _hf_hub_download_to_local_dir(
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 1487, in _hf_hub_download_to_local_dir
    _download_to_tmp_and_move(
  File "C:\Users\mlinke\AppData\Roaming\Python\Python310\site-packages\huggingface_hub\file_download.py", line 1872, in _download_to_tmp_and_move
    with incomplete_path.open("ab") as f:
  File "C:\Program Files\Python310\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'models\\phi-3-mini-4k-instruct-onnx\\.huggingface\\download\\cpu_and_mobile\\cpu-int4-rtn-block-32\\phi3-mini-4k-instruct-cpu-int4-rtn-block-32.onnx.1e1faf7ea6930f63caab12412f4a82c329eaddf6cce365e45c3cd00bb0547be8.incomplete'
```

### System info

```shell
- huggingface_hub version: 0.23.4
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.8
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\mlinke\.cache\huggingface\token
- Has saved token ?: False
- Configured git credential helpers: manager
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.3.1
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.8.2
- aiohttp: 3.9.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: C:\Users\mlinke\.cache\huggingface\hub
- HF_ASSETS_CACHE: C:\Users\mlinke\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\mlinke\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Hi @mlinke-ai , sorry you're facing this issue. Could you check that folder `models\\phi-3-mini-4k-instruct-onnx\\.huggingface\\download\\cpu_and_mobile\\cpu-int4-rtn-block-32\\` exists on your disk? If yes, I'm very surprised that the `incomplete_path` cannot be opened given that the `"ab"` flag when opening it should create it if it is missing. If the folder path does not exist, I would also be surprised but for a different reason (it shouldn't be able to reach this point in code without creating the folder :confused:)

**Comment by mlinke-ai** [comment]
Yes, the folder exists. It also contains all the `.metadata` files of the configs and tokenizer.

**Comment by Wauplin** [comment]
@mlinke-ai what happens if you run this snippet:

```py
from pathlib import Path
path = Path("models\\phi-3-mini-4k-instruct-onnx\\.huggingface\\download\\cpu_and_mobile\\cpu-int4-rtn-block-32\\phi3-mini-4k-instruct-cpu-int4-rtn-block-32.onnx.1e1faf7ea6930f63caab12412f4a82c329eaddf6cce365e45c3cd00bb0547be8.incomplete")

with path.open("ab") as f:
    pass
```

Do you also get the error?

**Comment by Wauplin** [comment]
Interesting, it looks like you are hitting the Windows max file path limit (see [docs](https://learn.microsoft.com/fr-fr/windows/win32/fileio/maximum-file-path-limitation?tabs=registry)). I just remembered we've seen this issue before. [Here is how to fix it](https://github.com/huggingface/huggingface_hub/blob/a626cc3dbcadbf83817c3c345a65510976399435/src/huggingface_hub/file_download.py#L1375) by prepending `"\\?\"` to the absolute path. Would you like to open a PR to fix this for the `_hf_hub_download_to_local_dir` path?

**Comment by Wauplin** [comment]
Thanks @mlinke-ai! Have a nice day too :)

**Comment by Leili** [comment]
Hi, I'm also facing this issue on a cluster. I download "whisper-medium" using huggingface-cli , and when loading the model it's looking for a missing ".incomplete" file. I've also tried downloading using "git clone" on my ubuntu machine (on Desktop to have a shorter path) but the error occurs regardless... Any help would be really appreciated!

**Comment by Wauplin** [comment]
@Leili sorry for the inconvenience. Can you open a new issue describing:
- what command you use to download
- do you download to the cache directory or to a local directory?
- which version of the package do you use?
- what is the exact error message you are getting (error message + stacktrace)?

With more information it'll be easier to investigate the issue.

**Comment by JorgeMIng** [comment]
I found the reason of the bug. In windows paths of more than 256 characters are not valid.

```python
from huggingface_hub import hf_hub_download

path="C:/Users/JorgeM/Desktop/projectos/graph_model/local_dir_long/1234567890123456789012345678901234567890/model/1234567890123456789012345678901234567890/model"

len(path)

hf_hub_download(repo_id="sentence-transformers/all-MiniLM-L6-v2",filename="sentence_bert_config.json",local_dir=path)
```
len(path) is lower than 256 characters.


```python
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\JorgeM\\Desktop\\projectos\\graph_model\\local_dir_long\\1234567890123456789012345678901234567890\\model\\1234567890123456789012345678901234567890\\model\\.cache\\huggingface\\download\\lGVMDuXJ-eOxWaZOviD6MtO-75w=.59d594003bf59880a884c574bf88ef7555bb0202.incomplete'
```

But the path of the file to create is 'C:\\Users\\JorgeM\\Desktop\\projectos\\graph_model\\local_dir_long\\1234567890123456789012345678901234567890\\model\\1234567890123456789012345678901234567890\\model\\.cache\\huggingface\\download\\lGVMDuXJ-eOxWaZOviD6MtO-75w=.59d594003bf59880a884c574bf88ef7555bb0202.incomplete'

which is longer than 256.

HuggingFace Hub "did" solve the issue by checking the input but does not check after with the final path for incomplete files.

```python
    # Some Windows versions do not allow for paths longer than 255 characters.
    # In this case, we must specify it as an extended path by using the "\\?\" prefix
    if os.name == "nt":
        if not str(local_dir).startswith("\\\\?\\") and len(os.path.abspath(lock_path)) > 255:
            file_path = Path("\\\\?\\" + os.path.abspath(file_path))
            lock_path = Path("\\\\?\\" + os.path.abspath(lock_path))
            metadata_path = Path("\\\\?\\" + os.path.abspath(metadata_path))
```


A solution is possible by modifying the function that creates the incomplete paths. You can check the system working properly with this alternative incomplete_path function.
```python
def __fix_paths_hub_download__():

    def incomplete_path(self, etag: str) -> Path:
        """Return the path where a file will be temporarily downloaded before being moved to `file_path`."""
        path = self.metadata_path.parent / f"{_short_hash(self.metadata_path.name)}.{etag}.incomplete"
        resolved = path.resolve()
        resolved_str = str(resolved)
        if len(resolved_str) > 255 and not resolved_str.startswith(r"\\?\\"):
            path = Path(r"\\?\{}".format(resolved_str))
        return path
    temporal_fix = incomplete_path
    original = huggingface_hub._local_folder.LocalDownloadFilePaths.incomplete_path
    huggingface_hub._local_folder.LocalDownloadFilePaths.incomplete_path=temporal_fix
    return original

def __restore_original_method__(original):
    huggingface_hub._local_folder.LocalDownloadFilePaths.incomplete_path=original
```

**Comment by Wauplin** [comment]
Hi @JorgeMIng , thanks for investigating this issue! Would you be up to open a PR to fix this directly in `huggingface_hub`? So it benefits everyone with out needing to monkeypatch the method. Thanks a lot in advance!
