### ISSUE TITLE
"most likely due to a circular import"

### ISSUE THREAD

**Issue by Zhaooyy** [huggingface/huggingface_hub#2387]
### Describe the bug

when i ues open-clip encoder, it raise error says"Hugging Face hub model specified but package not installed. Run `pip install huggingface_hub`", but my env already have hf_hub in it. And before this error, i've got lots of hf_hub import errors.

### Logs

```shell
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.file_download: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Error importing huggingface_hub.hf_api: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
Traceback (most recent call last):
  File "evaluate_iou_loc.py", line 340, in <module>
    evaluate(feat_dir, output_path, ae_ckpt_path, json_folder, mask_thresh, args.encoder_dims, args.decoder_dims, logger)
  File "evaluate_iou_loc.py", line 242, in evaluate
    clip_model = OpenCLIPNetwork(device)
  File "/data/data_ext1/zyy/LangSplat/eval/openclip_encoder.py", line 21, in __init__
    model, _, _ = open_clip.create_model_and_transforms(
  File "/data/data_ext1/conda/envs/GS/lib/python3.8/site-packages/open_clip/factory.py", line 399, in create_model_and_transforms
    model = create_model(
  File "/data/data_ext1/conda/envs/GS/lib/python3.8/site-packages/open_clip/factory.py", line 298, in create_model
    checkpoint_path = download_pretrained(pretrained_cfg, cache_dir=cache_dir)
  File "/data/data_ext1/conda/envs/GS/lib/python3.8/site-packages/open_clip/pretrained.py", line 645, in download_pretrained
    has_hf_hub(True)
  File "/data/data_ext1/conda/envs/GS/lib/python3.8/site-packages/open_clip/pretrained.py", line 611, in has_hf_hub
    raise RuntimeError(
RuntimeError: Hugging Face hub model specified but package not installed. Run `pip install huggingface_hub`.
```

### System info

```shell
cannot import name 'dump_environment_info' from 'huggingface_hub'
```

**Comment by Wauplin** [comment]
Hi @Zhaooyy, sorry you're facing this issue. Could you try to reinstall charset_normalizer which seems to be the culprit here?

```
pip install -U --force-reinstall charset-normalizer  
```

**Comment by Zhaooyy** [comment]
> Hi @Zhaooyy, sorry you're facing this issue. Could you try to reinstall charset_normalizer which seems to be the culprit here?
> 
> ```
> pip install -U --force-reinstall charset-normalizer  
> ```

it works! thx!

**Comment by Wauplin** [comment]
Great to hear! Have a nice day :hugs:
