### ISSUE TITLE
Problem with asyncc

### ISSUE THREAD

**Issue by freQuensy23-coder** [huggingface/huggingface_hub#2461]
### Describe the bug

Async Client raises error while generating last token

### Reproduction

```python
async def generate_llama3(system_input, user_input):
    client = AsyncInferenceClient(
        "meta-llama/Meta-Llama-3.1-8B-Instruct",
        token=os.getenv('HF_TOKEN')
    )
    async for message in await client.chat_completion(
            messages=[
                {"role": "system", "content": system_input},
                {"role": "user", "content": user_input}, ],
            max_tokens=256,
            stream=True,
    ):
        yield message.choices[0].delta.content
async for el in generate_llama3('You are AI assistant.', 'Count from 1 to 10'):
    print(el)
```

### Logs

```shell
Here
's
 the
 count
 from
 
1
 to
 
10
:
1
.
 One
2
.
 Two
3
.
 Three
4
.
 Four
5
.
 Five
6
.
 Six
7
.
 Seven
8
.
 Eight
9
.
 Nine
10
.
 Ten
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2023.2.3\plugins\python\helpers\pydev\pydevconsole.py", line 367, in runcode
    loop.run_until_complete(coro)
  File "C:\Users\alexey\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<input>", line 1, in <module>
  File "<input>", line 6, in generate_llama3
  File "C:\Users\alexey\PycharmProjects\history\venv\Lib\site-packages\huggingface_hub\inference\_common.py", line 334, in _async_stream_chat_completion_response
    output = _format_chat_completion_stream_output(item)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\PycharmProjects\history\venv\Lib\site-packages\huggingface_hub\inference\_common.py", line 352, in _format_chat_completion_stream_output
    json_payload = json.loads(payload.lstrip("data:").rstrip("/n"))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexey\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)
```

### System info

```shell
- huggingface_hub version: 0.24.5
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.11.7
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\alexey\.cache\huggingface\token
- Has saved token ?: True
- Who am I ?: freQuensy23
- Configured git credential helpers: manager
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.4.0
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: N/A
- gradio: 4.41.0
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: 2.8.2
- aiohttp: 3.10.4
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: C:\Users\alexey\.cache\huggingface\hub
- HF_ASSETS_CACHE: C:\Users\alexey\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\alexey\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Thanks for reporting @freQuensy23-coder and sorry for the inconvenience. The issue has already been reported in https://github.com/huggingface/huggingface_hub/issues/2455 and a fix being implemented in https://github.com/huggingface/huggingface_hub/pull/2458. I'll ship a patch release as soon as it gets merged.

**Comment by Wauplin** [comment]
The hot-fix release has been shipped: https://github.com/huggingface/huggingface_hub/releases/tag/v0.24.6. Upgrading `huggingface_hub` to the latest version should fix your problem :)
