### ISSUE TITLE
AsyncInferenceClient not closing connection properly when answer stream is not entierly consumed

### ISSUE THREAD

**Issue by tomjorquera** [huggingface/huggingface_hub#2493]
### Describe the bug

# Issue

When async streaming the LLM replies, if the anwer stream is not completely consumed I get warnings like

```python
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3cc7ad4a90>
Exception ignored in: <function ClientResponse.__del__ at 0x7f3cc7a7eca0>
```
once the frame is destroyed, indicating that the connection was not properly closed.

This is reproducible with the following example:

```python
import asyncio

from huggingface_hub import AsyncInferenceClient

model = ...  # NOTE: I'm using a self-hosted TGI instance

async def run():
    client = AsyncInferenceClient(model)
    answer_stream = await client.text_generation(
        "Between emacs and vim, the best editor is",
        stream=True,
    )

    # Stop here and do not consume the answer stream
    # some questions are best left unanswered
    return

asyncio.run(run())
```

The same issue also arises when partially consuming the stream, aka:

```python
async def run():
    client = AsyncInferenceClient(model)
    answer_stream = await client.text_generation(
        "Between emacs and vim, the best editor is",
        stream=True,
    )

    # only taking a sneak peek
    # (we all know the true answer anyways)
    await anext(answer_stream)

    return
```

# Possible cause

I traced the issue to 

https://github.com/huggingface/huggingface_hub/blob/893e88958cbc0ce0bcae4b20b8aa7cb437943c1e/src/huggingface_hub/inference/_common.py#L356-L359

Since we don't reach the end of the stream, `client.close` is never called.

# Solving attempts

In my specific case, I made it work somewhat by changing the code to:

```python
async with client:
    async for byte_payload in response.content:
        yield byte_payload.strip()
```

But it only works if the stream is *partially* consumed. I.e it will solve the issue in the second exemple, but not in the first.

Changing the code to
```python
try:
    async for byte_payload in response.content:
    yield byte_payload.strip()
finally:
    await client.close()
```
had a similar effect.

While it would be enough to solve my personal issue, I don't know if it is possible to solve the issue completely without changing the code more in depth :pensive: 

### Reproduction

```python
import asyncio

from huggingface_hub import AsyncInferenceClient

model = ...

async def run():
    client = AsyncInferenceClient(model)
    answer_stream = await client.text_generation(
        "Between emacs and vim, the best editor is",
        stream=True,
    )

    # Stop here and do not consume the answer stream
    # some questions are best left unanswered
    return

asyncio.run(run())
```

### Logs

```shell
(using `PYTHONASYNCIODEBUG=1`)


Exception ignored in: <function ClientResponse.__del__ at 0x7f48fb09aac0>
Traceback (most recent call last):
  File "/home/tom/.cache/pypoetry/virtualenvs/test-dzjSpnxa-py3.11/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 914, in __del__
    self._connection.release()
  File "/home/tom/.cache/pypoetry/virtualenvs/test-dzjSpnxa-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 191, in release
    self._connector._release(
  File "/home/tom/.cache/pypoetry/virtualenvs/test-dzjSpnxa-py3.11/lib/python3.11/site-packages/aiohttp/connector.py", line 687, in _release
    protocol.close()
  File "/home/tom/.cache/pypoetry/virtualenvs/test-dzjSpnxa-py3.11/lib/python3.11/site-packages/aiohttp/client_proto.py", line 71, in close
    transport.close()
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/selector_events.py", line 839, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f48fb29a050>
source_traceback: Object created at (most recent call last):
  File "/home/tom/test/test.py", line 22, in <module>
    asyncio.run(run())
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 1914, in _run_once
    handle._run()
  File "/home/tom/.pyenv/versions/3.11.2/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/tom/test/test.py", line 9, in run
    answer_stream = await client.text_generation(
  File "/home/tom/.cache/pypoetry/virtualenvs/test-dzjSpnxa-py3.11/lib/python3.11/site-packages/huggingface_hub/inference/_generated/_async_client.py", line 2177, in text_generation
    bytes_output = await self.post(json=payload, model=model, task="text-generation", stream=stream)  # type: ignore
  File "/home/tom/.cache/pypoetry/virtualenvs/test-dzjSpnxa-py3.11/lib/python3.11/site-packages/huggingface_hub/inference/_generated/_async_client.py", line 278, in post
    client = aiohttp.ClientSession(
```
```


### System info

```shell
- huggingface_hub version: 0.24.6
- Platform: Linux-6.10.6-amd64-x86_64-with-glibc2.40
- Python version: 3.11.2
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/tom/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: N/A
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: N/A
- pydantic: N/A
- aiohttp: 3.10.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/tom/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/tom/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/tom/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by tomjorquera** [comment]
Thanks for the fast reply @Wauplin !

I checked out your PR and can cofirm it solves the issue on my side :heart:

**Comment by Wauplin** [comment]
Hi @tomjorquera, PR https://github.com/huggingface/huggingface_hub/pull/2496 is merged! You can already use it by [installing from source](https://huggingface.co/docs/huggingface_hub/installation#install-from-source), otherwise it will be shipped in next release :)

**Comment by tomjorquera** [comment]
Sadly it seems I hit a related issue. I opened a new ticket https://github.com/huggingface/huggingface_hub/issues/2521

**Comment by Wauplin** [comment]
Thanks for opening a separate ticket. I'll have a lookt.
