### ISSUE TITLE
Hugging Face Space: Exception in ASGI application

### ISSUE THREAD

**Issue by erumoico** [huggingface/huggingface_hub#2515]
### Describe the bug

Hi! After factory rebuild of my Hugging Face Space, I can't do anything in my space. A new version 2.9 of pydantic has been released (5 hours ago), but I'm not sure if that's it.

After loading and when I click on any button, gr.Error("Connection errored out.") appears.

### Logs

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pydantic/type_adapter.py", line 279, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "/usr/local/lib/python3.10/site-packages/pydantic/type_adapter.py", line 121, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 766, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/site-packages/gradio/route_utils.py", line 782, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
  File "/usr/local/lib/python3.10/site-packages/fastapi/dependencies/utils.py", line 810, in request_body_to_args
    fields_to_extract = get_model_fields(first_field.type_)
  File "/usr/local/lib/python3.10/site-packages/fastapi/_compat.py", line 283, in get_model_fields
    return [
  File "/usr/local/lib/python3.10/site-packages/fastapi/_compat.py", line 284, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/usr/local/lib/python3.10/site-packages/fastapi/_compat.py", line 109, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
  File "/usr/local/lib/python3.10/site-packages/pydantic/type_adapter.py", line 266, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/usr/local/lib/python3.10/site-packages/pydantic/type_adapter.py", line 144, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pydantic/type_adapter.py", line 286, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
  File "/usr/local/lib/python3.10/site-packages/pydantic/type_adapter.py", line 104, in _get_schema
    schema = gen.generate_schema(type_)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 908, in _generate_schema_inner
    return self._annotated_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2025, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2104, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2186, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2182, in <lambda>
    lambda source, handler: handler(source)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2085, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1029, in match_type
    return self._match_generic_type(obj, origin)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1058, in _match_generic_type
    return self._union_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1378, in _union_schema
    choices.append(self.generate_schema(arg))
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

### System info

```shell
- huggingface_hub version: 0.24.6
- Platform: Linux-5.10.223-212.873.amzn2.x86_64-x86_64-with-glibc2.36
- Python version: 3.10.14
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/user/.cache/huggingface/token
- Has saved token ?: True
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: 0.1.8
- gradio: 4.42.0
- tensorboard: N/A
- numpy: 2.0.2
- pydantic: 2.9.0
- aiohttp: 3.10.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/user/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/user/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/user/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: True
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by erumoico** [comment]
Now (after 8 hours) I clicked the factory rebuild button again and it's working.

**Comment by parokshsaxena** [comment]
Hi @erumoico , I also started getting the same error in my repo. I tried factory rebuild but the error remains. Any other thing you tried?

Repo: https://huggingface.co/spaces/paroksh-mason/Virtual-Try-On

**Comment by erumoico** [comment]
Okay, maybe it's not solved. So I'm reopening the issue. Do you have same traceback in your log?

**Comment by parokshsaxena** [comment]
Thanks @erumoico, yes I have the same traceback.

I started a new discussion in my space and added the error details. Here is the link to that thread
https://huggingface.co/spaces/paroksh-mason/Virtual-Try-On/discussions/1

**Comment by yinanhe** [comment]
same question. The same code can run locally, but not in Huggingface Space.

**Comment by yinanhe** [comment]
> same question. The same code can run locally, but not in Huggingface Space.

I tried downgrading my pydantic to 2.7 and 2.8 and it still doesn't work.

**Comment by parokshsaxena** [comment]
Setting fastapi==0.112.2 in requirements has helped me as a temporary fix.

Ref:
https://discuss.huggingface.co/t/new-gradio-space-connection-errored-out/105509/3

**Comment by hanouticelina** [comment]
Hello, upgrading Gradio to `gradio==4.43.0` should fix the issue

**Comment by youishikawa** [comment]
> Hi @erumoico , I also started getting the same error in my repo. I tried factory rebuild but the error remains. Any other thing you tried?
> 
> Repo: https://huggingface.co/spaces/paroksh-mason/Virtual-Try-On
Even if it's helloworld, with the same Space, or duplicated Space, moved Space, all cause this error.
I can show you example Space below.

https://huggingface.co/spaces/Renecto/Virtual-Try-On?logs=container

All my Spaces, active in the morning JPT,  are dead by this error now.

**Comment by hanouticelina** [comment]
I'm closing this issue feel free to comment if encountering the same issue and I'll be glad to reopen

**Comment by GottfriedWilhelmLeibniz711** [comment]
===== Application Startup at 2024-11-23 07:36:34 =====

* Running on local URL:  http://0.0.0.0:7860, with SSR ⚡
INFO:     Started server process [25]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8002 (Press CTRL+C to quit)

To create a public link, set `share=True` in `launch()`.
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.10/site-packages/starlette/_utils.py", line 76, in collapse_excgroups
  |     yield
  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
