### ISSUE TITLE
Keyerror 'safe' in load_dataset

### ISSUE THREAD

**Issue by binarycrayon** [huggingface/huggingface_hub#2524]
### Describe the bug

It seems huggingface api just rolled out a breaking change?
what hf api used to produce
```
{'blobId': 'xxxxxxx', 'name': 'README.md', 'safe': True, 'indexed': False, 'avScan': {'virusFound': False, 'virusNames': None}, 'pickleImportScan': None}
```
has now become
```
{'hf': {'blobId': 'xxxxxxx', 'name': 'README.md', 'safe': True, 'indexed': False, 'avScan': {'virusFound': False, 'virusNames': None}, 'pickleImportScan': None}}
```

### Reproduction

load_dataset on any dataset

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/load.py", line 2606, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/load.py", line 2277, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/load.py", line 1923, in dataset_module_factory
    raise e1 from None
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/load.py", line 1905, in dataset_module_factory
    ).get_module()
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/load.py", line 1221, in get_module
    dataset_readme_path = cached_path(
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 211, in cached_path
    output_path = get_from_cache(
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 583, in get_from_cache
    response = fsspec_head(url, storage_options=storage_options)
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 361, in fsspec_head
    return fs.info(path)
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/huggingface_hub/hf_file_system.py", line 540, in info
    paths_info = self._api.get_paths_info(
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3145, in get_paths_info
    paths_info = response.json()
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 3146, in <listcomp>
    return [
  File "/home/yxue/micromamba/envs/unsloth/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 638, in __init__
    security = BlobSecurityInfo(
KeyError: 'safe'
```

### System info

```shell
- huggingface_hub version: 0.24.6
- Platform: Linux-5.10.0-26-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.14
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/yxue/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: yxue-jamandtea
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.4.0
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: 0.1.8
- gradio: N/A
- tensorboard: N/A
- numpy: 2.1.1
- pydantic: N/A
- aiohttp: 3.10.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/yxue/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/yxue/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/yxue/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10

{'huggingface_hub version': '0.24.6', 'Platform': 'Linux-5.10.0-26-cloud-amd64-x86_64-with-glibc2.31', 'Python version': '3.10.14', 'Running in iPython ?': 'No', 'Running in notebook ?': 'No', 'Running in Google Colab ?': 'No', 'Token path ?': '/home/yxue/.cache/huggingface/token', 'Has saved token ?': True, 'Who am I ?': 'yxue-jamandtea', 'Configured git credential helpers': 'store', 'FastAI': 'N/A', 'Tensorflow': 'N/A', 'Torch': '2.4.0', 'Jinja2': '3.1.4', 'Graphviz': 'N/A', 'keras': 'N/A', 'Pydot': 'N/A', 'Pillow': 'N/A', 'hf_transfer': '0.1.8', 'gradio': 'N/A', 'tensorboard': 'N/A', 'numpy': '2.1.1', 'pydantic': 'N/A', 'aiohttp': '3.10.5', 'ENDPOINT': 'https://huggingface.co', 'HF_HUB_CACHE': '/home/yxue/.cache/huggingface/hub', 'HF_ASSETS_CACHE': '/home/yxue/.cache/huggingface/assets', 'HF_TOKEN_PATH': '/home/yxue/.cache/huggingface/token', 'HF_HUB_OFFLINE': False, 'HF_HUB_DISABLE_TELEMETRY': False, 'HF_HUB_DISABLE_PROGRESS_BARS': None, 'HF_HUB_DISABLE_SYMLINKS_WARNING': False, 'HF_HUB_DISABLE_EXPERIMENTAL_WARNING': False, 'HF_HUB_DISABLE_IMPLICIT_TOKEN': False, 'HF_HUB_ENABLE_HF_TRANSFER': False, 'HF_HUB_ETAG_TIMEOUT': 10, 'HF_HUB_DOWNLOAD_TIMEOUT': 10}
```

**Comment by osanseviero** [comment]
Sorry for the issues, a fix was deployed some hours ago
