### ISSUE TITLE
NameError: name 'packaging' is not defined

### ISSUE THREAD

**Issue by hengxt** [huggingface/huggingface_hub#2609]
### Describe the bug

dependence：
```
huggingface-hub     0.25.2
packaging           24.1
ultralytics   8.1.34
```

<img width="1334" alt="8c37aa16df496281cf871c1138d393f" src="https://github.com/user-attachments/assets/27f78f33-4b67-42d8-95d5-8c7192cab183">

### Reproduction

from ultralytics import YOLOv10
import packaging

model = YOLOv10.from_pretrained('jameslahm/yolov10n')
source = 'http://images.cocodataset.org/val2017/000000039769.jpg'
model.predict(source=source, save=True)

### Logs

```shell
Traceback (most recent call last):
  File "C:\Users\A\.conda\envs\Circuit2Netlist\lib\site-packages\huggingface_hub\hub_mixin.py", line 808, in _from_pretrained
    return cls._load_as_safetensor(model, model_file, map_location, strict)
  File "C:\Users\A\.conda\envs\Circuit2Netlist\lib\site-packages\huggingface_hub\hub_mixin.py", line 832, in _load_as_safetensor
    if packaging.version.parse(safetensors.__version__) < packaging.version.parse("0.4.3"):  # type: ignore [attr-defined]
NameError: name 'packaging' is not defined
```
```


### System info

```shell
- huggingface_hub version: 0.25.2
- Platform: Windows-10-10.0.19045-SP0
- Python version: 3.9.20
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Running in Google Colab Enterprise ?: No
- Token path ?: C:\Users\A\.cache\huggingface\token
- Has saved token ?: True
- Who am I ?: 
- Configured git credential helpers: manager
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.4.1
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.26.4
- pydantic: N/A
- aiohttp: N/A
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: C:\Users\A\.cache\huggingface\hub
- HF_ASSETS_CACHE: C:\Users\A\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\A\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment]
Thanks for reporting @hengxt, I opened https://github.com/huggingface/huggingface_hub/pull/2610 to fix it.
