### ISSUE TITLE
ModuleNotFoundError: No module named 'huggingface_hub.inference._types'

### ISSUE THREAD

**Issue by silvacarl2** [huggingface/huggingface_hub#2717]
### Describe the bug

ModuleNotFoundError: No module named 'huggingface_hub.inference._types'

### Reproduction

from llama_index.llms.huggingface import HuggingFaceLLM

### Logs

```shell
python chatgpt-rag-test.py
Traceback (most recent call last):
  File "/mnt/d/Dropbox/Developer-Tools/RAG_Techniques/chatgpt-rag-test.py", line 3, in <module>
    from llama_index.llms.huggingface import HuggingFaceLLM
  File "/home/silvacarl/.local/lib/python3.10/site-packages/llama_index/llms/huggingface/__init__.py", line 1, in <module>
    from llama_index.llms.huggingface.base import (
  File "/home/silvacarl/.local/lib/python3.10/site-packages/llama_index/llms/huggingface/base.py", line 8, in <module>
    from huggingface_hub.inference._types import ConversationalOutput
ModuleNotFoundError: No module named 'huggingface_hub.inference._types'
```

### System info

```shell
Name: huggingface-hub
Version: 0.27.0
Summary: Client library to download and publish models, datasets and other repos on the huggingface.co hub
Home-page: https://github.com/huggingface/huggingface_hub
Author: Hugging Face, Inc.
Author-email: julien@huggingface.co
License: Apache
Location: /home/silvacarl/.local/lib/python3.10/site-packages
Requires: filelock, fsspec, packaging, pyyaml, requests, tqdm, typing-extensions
Required-by: accelerate, cached_path, ctransformers, datasets, diffusers, evaluate, faster-whisper, gradio, gradio_client, langchain-huggingface, lightning-whisper-mlx, llama-index-llms-huggingface, llama-index-llms-huggingface-api, llama_toolchain, modelscope, moshi, optimum, outetts, peft, pyannote.audio, sentence-transformers, skops, speechbrain, text-generation, text-generation-server, timm, tokenizers, transformers, vocos
```

**Comment by hanouticelina** [comment]
Hi @silvacarl2, the issue you're encountering occurs because `ConversationalOutput` was removed from `huggingface_hub` in version `0.25.0`, and you're running version `0.27.0`. However, `llama-index` requires a version that is >=0.23.0 and <0.24.0 (see [here](https://github.com/run-llama/llama_index/blob/4b50ce8a6578c03fe8454b2771930fe19547875f/llama-index-integrations/llms/llama-index-llms-huggingface/pyproject.toml#L35)), so downgrading `huggingface_hub` to an earlier version should fix your issue.

To resolve this, you can try downgrading `huggingface_hub` :
```bash
pip install "huggingface-hub>=0.23.0,<0.24.0"
```
or create a new virtual environment and run:
```bash
pip install llama-index-integrations/llms/llama-index-llms-huggingface
```

I'm closing this issue but feel free to comment if you have any other related question 🤗
