### ISSUE TITLE
For HTTP request errors, add response to exception message

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface_hub#751]
**Is your feature request related to a problem? Please describe.**

Most of the time, hf.co sends a JSON response along with HTTP error codes. But it's not shown in the stack trace:

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:5564/api/repos/delete
```

Which leads hf.co to send a 409 here even though it's really not the correct HTTP code (see https://github.com/huggingface/moon-landing/issues/2272)

**Describe the solution you'd like**
Add the error message from hf.co when available.

I tried this in `HfApi.delete_repo`: 

```python
       try:
            r.raise_for_status()
        except requests.exceptions.RequestException as e:
            message = e.response.json()["error"]
            import sys
            raise type(e)(str(e) + " - " + message).with_traceback(sys.exc_info()[2])
```

This seems to work, but I suck very much at Python and it's a handful of lines. (and would cause an unrelated error when `response.json()` fails)

cc @SBrandeis @osanseviero @LysandreJik

**Comment by julien-c** [comment]
maybe tagging @adrinjalali too on this

**Comment by adrinjalali** [comment]
Wouldn't this be maybe better?

```py
       try:
            r.raise_for_status()
        except requests.exceptions.RequestException as e:
            raise type(e)(message) from e
```

**Comment by adrinjalali** [comment]
The *cause* is shown nicely though, e.g:

```py
In [1]: try:
   ...:     raise ValueError("test")
   ...: except ValueError as e:
   ...:     raise type(e)("new msg") from e
   ...: 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 1>()
      1 try:
----> 2     raise ValueError("test")
      3 except ValueError as e:

ValueError: test

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 1>()
      2     raise ValueError("test")
      3 except ValueError as e:
----> 4     raise type(e)("new msg") from e

ValueError: new msg
```

And I think it's the way one is supposed to raise exceptions from another one?

**Comment by coyotte508** [comment]
Ok :)

Python is not my language!

**Comment by severo** [comment]
> This loses the full stack trace I think

no, `from e` ensures the stack trace is not cut.

**Comment by julien-c** [comment]
Ok so are we in agreement on this? Who wants to open a PR?

**Comment by adrinjalali** [comment]
I'll send a PR

**Comment by adrinjalali** [comment]
@coyotte508 do you have a minimal reproducing code for me to use?

**Comment by coyotte508** [comment]
@adrinjalali 

In in `HfApi.delete_repo`, instead of

```
            r.raise_for_status()
```

I edited to:

```
       try:
            r.raise_for_status()
        except requests.exceptions.RequestException as e:
            message = e.response.json()["error"]
            raise type(e)(str(e)) from e
```

My python terminal was something like:

```
api = new HfApi();
api.delete_repo("repo-that-does-not-exist")
```

On that, hf.co will respond with a json containing `{"error": "..."}`. The new code should show the error message from hf.co (which will still be about a conflict), which is different from the current code.

**Comment by adrinjalali** [comment]
Trying this out, there seems to be a difference between the staging and the live envs. On live, this is what I have:

```bash
curl -XDELETE https://huggingface.co/api/repos/delete \
  -H"{'authorization': 'Bearer ---token---'}" \
  -d "{'name': 'repo-that-does-not-exist', 'organization': None}" 
{"error":"Unauthorized"}%
```

while on staging:

``` bash
$ curl -XDELETE https://moon-staging.huggingface.co/api/repos/delete \
  -H"{'authorization': 'Bearer ---token---'}" \
  -d "{'name': 'repo-that-does-not-exist', 'organization': None}"
```

I get no errors, which is odd cause sending the same request in the test file results in this error:

    HTTPError('409 Client Error: Conflict for url: [https://moon-staging.huggingface.co/api/repos/delete]()')

But the `e.response.text` is just `Conflict` and not a json-like string. For me to send the PR first we need to fix the staging backend I think (@coyotte508 could you help with that?)

Regardless, against live, would this be a reasonable exception for you?

```pytnon
from huggingface_hub import HfApi
api = HfApi()
api.delete_repo("repo-that-does-not-exist")
```

``` python-traceback
Traceback (most recent call last):
  File "/home/adrin/Projects/hf/hub/src/huggingface_hub/hf_api.py", line 1245, in delete_repo
    r.raise_for_status()
  File "/home/adrin/miniforge3/envs/hf-sklearn/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://huggingface.co/api/repos/delete

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/1.py", line 3, in <module>
    api.delete_repo("repo-that-does-not-exist")
  File "/home/adrin/Projects/hf/hub/src/huggingface_hub/hf_api.py", line 1248, in delete_repo
    raise type(e)(message) from e
requests.exceptions.HTTPError: Conflict
```

**Comment by adrinjalali** [comment]
> There were a few errors in the curl command, with this it should work:
>
> ```
> curl -X DELETE -H "Authorization: Bearer ---token---" -d "{'name': 'repo-does-not-exist'}" https://huggingface.co/api/repos/delete   
> ```

I think that's because linux's POSIX is more relaxed on the order of arguments than MacOs's ;)

> But I do get a JSON response :thinking: : 

What should the message look like? Since we're testing that the right message is raised, the test in the PR needs to know what to expect.
