### ISSUE TITLE
Better error messages when pushing/pulling to/from the hub

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#989]
When using some methods of HfApi, the error messages could be improved as they're a bit cryptic now.

## Example 1

When using the `hf_hub_download` method to pull something from the hub, as follows: 

```
file_path = hf_hub_download(repo_id="hf-internal-testing/spaghetti-video-8-frames", filename="pixel_values.pt")
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/niels/python_projects/transformers/src/transformers/models/x_clip/convert_x_clip_original_pytorch_to_hf.py", line 201, in <module>
    convert_xclip_checkpoint(args.checkpoint_url, args.model_name, args.pytorch_dump_folder_path)
  File "/home/niels/python_projects/transformers/src/transformers/models/x_clip/convert_x_clip_original_pytorch_to_hf.py", line 164, in convert_xclip_checkpoint
    file_path = hf_hub_download(repo_id="hf-internal-testing/spaghetti-video-8-frames", filename="pixel_values.pt")
  File "/home/niels/python_projects/transformers/env/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1020, in hf_hub_download
    _raise_for_status(r)
  File "/home/niels/python_projects/transformers/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 78, in _raise_for_status
    raise RepositoryNotFoundError(
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error: Repository Not Found for url: https://huggingface.co/hf-internal-testing/spaghetti-video-8-frames/resolve/main/pixel_values.pt. If the repo is private, make sure you are authenticated. (Request ID: taN90NWL5XJ4xo752a45_)
``` 
However, in this case the error occurs because the repository type is a dataset, not a model. Hence, I need to specify `repo_type="dataset"`.

## Example 2
Similarly, when using the `upload_file` method and pushing to a repo that doesn't exist yet, I get a similar 401 HTTP error, rather than a message saying "the `upload_file` method assumes the repo already exists, please make sure it exists on the hub". I assume the same would need to be added for the `upload_folder` method (and perhaps others as well).

**Comment by Wauplin** [comment]
Hi @NielsRogge, sorry for not getting back to you before on this issue. I am not exactly sure to understand if the problem is that `RepositoryNotFoundError` is a Client error 401 or that the messages are not clear, or both.

1. Would a traceback like this be preferable to you in example 1 ?

```
Traceback (most recent call last):
  File "/home/niels/python_projects/transformers/src/transformers/models/x_clip/convert_x_clip_original_pytorch_to_hf.py", line 201, in <module>
    convert_xclip_checkpoint(args.checkpoint_url, args.model_name, args.pytorch_dump_folder_path)
  File "/home/niels/python_projects/transformers/src/transformers/models/x_clip/convert_x_clip_original_pytorch_to_hf.py", line 164, in convert_xclip_checkpoint
    file_path = hf_hub_download(repo_id="hf-internal-testing/spaghetti-video-8-frames", filename="pixel_values.pt")
  File "/home/niels/python_projects/transformers/env/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1020, in hf_hub_download
    _raise_for_status(r)
  File "/home/niels/python_projects/transformers/env/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 78, in _raise_for_status
    raise RepositoryNotFoundError(
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error: Repository Not Found. (Request ID: taN90NWL5XJ4xo752a45_)

Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated. 
URL: https://huggingface.co/hf-internal-testing/spaghetti-video-8-frames/resolve/main/pixel_values.pt
```

2. In the case of `upload_file` (or `upload_folder`) to a non-existant repository, would you suggest to have a custom exception other than `RepositoryNotFound` or just to have a different message ?
I get the purpose of `"the upload_file method assumes the repo already exists, please make sure it exists on the hub"` but then we forget about the other advices (repo type should be set, authentification required if private repo). What would be the ideal stack trace for you in `upload_file` case ?

**Comment by NielsRogge** [comment]
For 1, yes, the error message is much clearer.

For 2, I'd just create a longer error message. Can't we add both "repo should exist on the hub" and "repo type should be set" etc.? The more informative the message, the better.

**Comment by cakiki** [comment]
I've had this same issue with other functions/ `HfApi` methods that have the `repo_type` not set to `dataset`.

**Comment by cakiki** [comment]
I've had this same issue with other functions/ `HfApi` methods that have the `repo_type` not set to `dataset`.
